### PR TITLE
feat: display package peer deps

### PR DESCRIPTION
**Pull request by stephanebachelier**
**Type:** feature

The following has been addressed in the PR:

*  Unit tests are included in the PR

**Description:**

Append Peer dependencies on PackageSidebar.

### CODE REVIEW

**Comment by ayusharma** [comment]
@juanpicado Let's keep this PR on 4.x, anyway, we can not merge in master. @stephanebachelier we are doing refactoring in webui so most of the things will change.

**Comment by juanpicado** [comment]
Let's talk about this in person later on @ayusharma. This is a potential conflict. I think should be con based on `4.x` branch. @stephanebachelier thanks for the PR please I'll keep you in touch what we decided how to handle this.

**Comment by stephanebachelier** [comment]
@juanpicado @ayusharma I can rebase (redo?) my work for the 4.x branch.

**Comment by ayusharma** [comment]
@stephanebachelier I'll let you asap know after discussing it with @juanpicado 😀

**Comment by ayusharma** [comment]
@stephanebachelier  I had a discussion with @juanpicado . We'll review it and ship it with 3.x

**Comment by juanpicado** [comment]
Congrats @stephanebachelier  🥇 
released on `verdaccio@3.9.0`

**Pull request merged**
