### PR TITLE
fix: update request dependency

### PR DESCRIPTION
**Pull request by juanpicado**
Trying to fix https://app.snyk.io/vuln/SNYK-JS-AJV-584908

### CODE REVIEW

**Comment by juanpicado** [comment]
Test are failing

**Comment by DanielRuf** [comment]
> Test are failing

Is it due to the dependency update? Because then it would be a breaking change.

**Comment by DanielRuf** [comment]
In general request is deprecated afaik. Didn't we switch to some alternative somewhere?

Also I do not see any 2.88.2 tag at https://github.com/request/request/tags.

**Comment by DanielRuf** [comment]
Hm, what could cause this?

https://gist.github.com/DanielRuf/8f337f6a85f5e4def3a55d0d00f56ee9

Also see https://github.com/request/request/issues/3333

**Comment by DanielRuf** [comment]
Not sure if this was an issue with npmjs, I restarted the tests:

grafik

**Comment by DanielRuf** [comment]
We should probably bisect `request` locally (by installing from the GitHub repo request/request and checkout different points in the history after the 2.88.0 release). Can you do that @juanpicado? I'm currently unsure if it is caused by request or if it is unrelated and caused by something else.

**Comment by DanielRuf** [comment]
Ok, let's wait until npmjs has resolved the current issues because I see some issues with oterh packages too.

https://status.npmjs.org/

grafik

grafik

**Comment by DanielRuf** [comment]
Seems to be related to the npmjs outage (one current example):
https://twitter.com/gandarla/status/1291287480163897346

grafik

**Comment by DanielRuf** [comment]
Seems to be related to the npmjs outage (one current example):
https://twitter.com/gandarla/status/1291287480163897346

grafik

And more: https://twitter.com/search?q=npm%20404&src=typed_query&f=live

**Comment by DanielRuf** [comment]
Triggering a new build.

**Comment by juanpicado** [comment]
> We should probably bisect `request` locally (by installing from the GitHub repo request/request and checkout different points in the history after the 2.88.0 release). Can you do that @juanpicado? I'm currently unsure if it is caused by request or if it is unrelated and caused by something else.

I've experienced this in the past, for such reason I created this PR to see whether the issue still persists. My willingness was just to get rid of `request` since I have no clue why a patch is breaking the project.

Currently are two initiatives to replace `request`, both uses `node-fetch`:

* https://github.com/verdaccio/monorepo/pull/367
* https://github.com/verdaccio/verdaccio/pull/1818 (5.x)

I did not want to do it in master to avoid unexpected issues and keeping it stable. So, I'd try the following

* Try to find out why the latest of `request` breaking everything
* If the first option fails, I might need to move to another library in `master`

I think just leave it like this is not an option, security matters.

**Comment by DanielRuf** [comment]
>     * Try to find out why the latest of `request` breaking everything

Probably not caused by request as described in the comments. Still trying to get the tests running - the issue is caused by npmjs, not request.

**Comment by DanielRuf** [comment]
> I think just leave it like this is not an option, security matters.

No need to rush, especially as npmjs is still fixing this issue with the 404s.

**Comment by DanielRuf** [comment]
Hm, I wonder why we still use CircleCI which seems to run the same tasks. @juanpicado

**Comment by DanielRuf** [comment]
I'm not sure but the issue with npmjs should be resolved now. Can you try a second commit which reverts the first one so we can see if the tests fail even without this change @juanpicado? If this is the case then we still have some issue with npmjs. If not, then it is likely an issue caused by the request update (which is hopefully not the case).

**Comment by juanpicado** [comment]
> I'm not sure but the issue with npmjs should be resolved now. Can you try a second commit which reverts the first one so we can see if the tests fail even without this change @juanpicado? If this is the case then we still have some issue with npmjs. If not, then it is likely an issue caused by the request update (which is hopefully not the case).

Done.

I gave up with `request`, the last release is so obtuse. I went through each last commit with `yarn link` and I could not reproduce the error.

**Comment by DanielRuf** [comment]
Ok, I've rerun the previous commit and it still fails. So I guess request 2.88.2 is broken and it's unclear what was released there and also how it was done.

**Comment by juanpicado** [comment]
Regarding the vulnerability, it seems related with `har` validator. But we do not use it and also we don't allow it.

https://github.com/request/request#support-for-har-12

So, I guess I can close this. Second thoughts @DanielRuf ?

**Comment by DanielRuf** [comment]
Right, see also https://github.com/request/request/issues/3330. So 2.88.2 would not resolve this. I vote for closing this PR and focus on one of the alternative PRs to replace request with another package.

**Pull request closed without merging**
