### PR TITLE
Indiescripter/upgrade website docusaurus

### PR DESCRIPTION
**Pull request by indiescripter**
Spun up the website server locally and previewed in browser; cross fingers what I saw is what's expected.
Hope this good to go ;)

### CODE REVIEW

**Review by semoal — APPROVED** [review]
Lgtm 🤟🏻

**Comment by indiescripter** [comment]
Thx @semoal for super fast review. Just rebased against master and force pushed my local branch. GH check is running verrrry slow atm.

**Review by juanpicado — DISMISSED** [review]

**Comment by indiescripter** [comment]
Added another commit to pin remaining unpinned dep versions. Only one dep patch version changed in reality.
Did this as a practicality to restart GH CI which hung for 3 hours after only completing 2 checks.
Good to review & go again @juanpicado :)

**Comment by indiescripter** [comment]
Just rebased against new master with #2418 included; regenerated pnpm lockfile to resolve conflicts but CI is taking a verrrrry long time again. Did you see my note about having to kill CI yesterday after 3 hrs but pushing up a trivial commit?

**Review by juanpicado — APPROVED** [review]
LGTM

**Pull request merged**
