### PR TITLE
add uplink list feat

### PR DESCRIPTION
**Pull request by joebnb**
add uplink pacakge to db when visit uplink package metadata

https://github.com/verdaccio/verdaccio/discussions/706

### CODE REVIEW

**Comment by juanpicado** [comment]
hi @joebnb 

could you describe why do you want this and why? I need more context. What I understand by far is you won't want to some uplinks show up on the UI or being stored at all in the manifest,  that's right?

**Comment by joebnb** [comment]
> hi @joebnb
> 
> could you describe why do you want this and why? I need more context. What I understand by far is you won't want to some uplinks show up on the UI or being stored at all in the manifest, that's right?

i have several uplinks,npmjs and 3-5 private npm repository to uplink, and i want to show the cached private npm packages in package list, therefore add package name in db when somebody visit it

**Comment by juanpicado** [comment]
I understand your objective, but I think this is not the way to achieve that. The database is just a JSON file, if we allow this you would end up with a huge JSON file eventually would get slow really quickly, since many endpoints check that file constantly. 

The objective of the .db-verdaccio.json is only to host private packages.

To display all packages on the UI as I reported in the ticket required more work to be performant, "hack" the database is just a workaround that would work only work while until get unmanageable.

**Comment by joebnb** [comment]
> I understand your objective, but I think this is not the way to achieve that. The database is just a JSON file, if we allow this you would end up with a huge JSON file that eventually (even if is opt-in, would allow side effects) would get slow really quickly since many endpoints check that file constantly.
> 
> The objective of the `.db-verdaccio.json` is only to host private packages.
> 
> To display all packages on the UI as I reported in the ticket required more work to be performant, "hack" the database is just a workaround that would work only work while until get unmanageable.
> 
> Unfortunately, I don't have in mind a better solution, that ticket you referred #706 has been open for a while, a few blockers were solved already but hasn't arrived yet a solution that does is performant enough in long term.
> 
> cc: @verdaccio/collaborators

total agree it may cause slow,and it irreversible since pollution db，but for me  this change is acceptable tiny.therefore i plan to build my version locally（maybe）.

did you consider separate verdaccio db like storage plugin with search api included(current search in browser may also not good for enterprise use)，and upgrade verdaccio db to sqllite as default,other‘s can develop some like Mariadb or other ,this sql  relation db also provide a good search engine for indexing packages.i think this suggestion is acceptable for you,the db structure still array like,but it can extension search with high performance.and i believe verdaccio need a real db now or feature, why not add this in v6？

**Comment by juanpicado** [comment]
> > I understand your objective, but I think this is not the way to achieve that. The database is just a JSON file, if we allow this you would end up with a huge JSON file that eventually (even if is opt-in, would allow side effects) would get slow really quickly since many endpoints check that file constantly.
> > The objective of the `.db-verdaccio.json` is only to host private packages.
> > To display all packages on the UI as I reported in the ticket required more work to be performant, "hack" the database is just a workaround that would work only work while until get unmanageable.
> > Unfortunately, I don't have in mind a better solution, that ticket you referred #706 has been open for a while, a few blockers were solved already but hasn't arrived yet a solution that does is performant enough in long term.
> > cc: @verdaccio/collaborators
> 
> total agree it may cause slow,and it irreversible since pollution db，but for me this change is acceptable tiny.therefore i plan to build my version locally（maybe）.
> 
> did you consider separate verdaccio db like storage plugin with search api included(current search in browser may also not good for enterprise use)，and upgrade verdaccio db to sqllite as default,other‘s can develop some like Mariadb or other 

There is a Storage API for custom DB plugins, I guess that should satisfy most of the request regarding using your own database.

> ,this sql relation db also provide a good search engine for indexing packages.i think this suggestion is acceptable for you,the db structure still array like,

Anyway, the list of features request is huge as any other OSS software, but no the man power, so the current roadmap #1690 still have pieces from years ago.

The current approach is to improve the architecture and delegate as much logic possible to plugins, it is not currently perfect (roadmap is full of plugins legitimate and valid feature requests).

> but it can extension search with high performance.and i believe verdaccio need a real db now or feature, why not add this in v6？

Verdaccio is not made enterprise-first, is developer-first. So single JSON file database is more than enough for majority, but like I said, all the improvements made over the years are in the direction enterprises could build their own stuff via their own plugins while (this is very important) **keeping simplicity for DX intact as the first day**.

I just improved search api endpoint recently #2340, updated search UI component #2448  and I'm willing to improve it more so can consume it directly from #2340 (same endpoint that uses npm search) that allows search ANY package, either private or cache.

I appreciate your suggestions of course, don't get it wrong, :) I'd suggest, create one Discussion for every one of them and discuss them separately, on this PR I think is the wrong place. Please review the roadmap, contribute with your ideas, not everything would go to v6 because is impossible, but whatever is included, I'd like to make it good.

**Pull request closed without merging**
