### PR TITLE
docs: add docs for theme and filter plugins

### PR DESCRIPTION
**Pull request by juanpicado**
- Add better documentation for building theme plugins
- Add better documentation for building filter plugins

### CODE REVIEW

**Comment by mbtools** [comment]
I read the updated pages. Great improvement, thank you!

**Comment by juanpicado** [comment]
> I read the updated pages. Great improvement, thank you!

Thank u !! more to come soon :) Any place you consider needs more polish?

**Comment by mbtools** [comment]
- It's not clear if theme/filter plugins also support naming with `@scope`. 
- I like the storybook view of components. However, if implementing a new theme, I would prefer to start from the existing ui-theme. Since it's part of this big repo now, is there a clever way to clone/fork just the ui-theme as a base for creating a theme plugin? Alternatively, an example repo for a theme would be great. 
- I'm struggling mostly with colors of elements. But it sounds like css can't be part of a custom theme yet. 

PS: I'm good at adapting existing code (in various languages), not great at developing something from scratch. So working examples even if very small are always the best.

PPS: Maybe rename "Search Plugins" (sounds like something to implement) to "Search for Plugins"

**Comment by juanpicado** [comment]
> * It's not clear if theme/filter plugins also support naming with `@scope`.
> * I like the storybook view of components. However, if implementing a new theme, I would prefer to start from the existing ui-theme. Since it's part of this big repo now, is there a clever way to clone/fork just the ui-theme as a base for creating a theme plugin? Alternatively, an example repo for a theme would be great.

A template repo os a good idea, but for the other side increase maintenance cost, anyhow it's a doable option that renovate might helps. To be honest I don't know how many devs are having their own theme, so components is an experiment and was easy to do. The ui was in it own repo https://github.com/verdaccio/ui but was very hard to ship changes.

> * I'm struggling mostly with colors of elements. But it sounds like css can't be part of a custom theme yet.

Yes, at initial stage I just wanted to extract components, still the scaffolding o the app remains on the plugin, I'm trying to polish my frontend skills here to have something more flexible and easy to use, feedback is always great.

> 
> PS: I'm good at adapting existing code (in various languages), not great at developing something from scratch. So working examples even if very small are always the best.

The plugin generator is oriented in that direction, hopefully some day I can write more about plugins I still have so many things I'd like to write down with examples.

> 
> PPS: Maybe rename "Search Plugins" (sounds like something to implement) to "Search for Plugins"

Thank u, I take notes.

**Pull request merged**
