### PR TITLE
Replace YAML package definitions with standard package.json, fix dependencies

### PR DESCRIPTION
**Pull request by steve-p-com**
Included in this:

- removed yapm
- replaced package.yaml with standard package.json
- removed post-install reconstruction of npm-shrinkwrap file, which defeats the purpose of the file
- removed JSON5 body parser (four year old proposed extensions to JSON which have not yet happened) and reinstated standard Express body parser
- reverted Express 5 alpha to Express 4 for maximum stability
- replaced all out of date version dependencies in the new package.json with the latest versions to clean up the warnings

The motivation is to become more standards-compliant to assist contributors, and bring all dependencies up to the latest stable release.

Note: I have not changed the `author` section in `package.json`, which needs attention afterwards. I have left the licence as [WTFPL](http://spdx.org/licenses/WTFPL.html) which I'm not personally a fan of, but perhaps merits a later debate.

### CODE REVIEW

**Comment by steve-p-com** [comment]
Finally. @trentearl do you think you might be able to use this in future:

https://help.github.com/articles/about-pull-request-merge-squashing/

Fighting git and github all the time is beginning to get old! And it keeps deleting the pull requests when reverting them. It seems like you can probably squash multiple commits into one when you merge, which is likely to be safer. That time round, I lost the changes, then got them back with insurmountable merge conflicts. Anyway, it's done now.

**Comment by andrewjensen** [comment]
+1 for using the pull request merge squashing. I think that asking for single-commit PRs will scare away potential contributors. Letting Github handle this will take the burden off of the community and the project will be able to grow.

**Comment by trentearl** [comment]
@steve-p-com  @andrewjensen  Yes! I will look into that and try to make it easier on you next time

**Comment by trentearl** [comment]
@steve-p-com this looks great, Thanks! also it did remove the race test errors. Do you know why?

**Comment by steve-p-com** [comment]
I don't know why it fixed those race condition test failures. Perhaps they were caused by the alpha version of Express it was using, or maybe one of the many out of date packages could have had a fix in the meantime. I notice there are some TODO comments in the code mentioning potential race conditions as well. 

Unfortunately the code isn't structured in a way that makes for easy legibility, maintainability or extensibility, so it will be challenging to modernise parts of it. I think the author was going for a record in the number of callback levels or something. I don't mind a challenge though!

**Comment by trentearl** [comment]
This is an old issue but I was wondering if you have any idea of improving the legibility.

Do you mean a promise based API as opposed to a callback?

**Comment by steve-p-com** [comment]
A promise-based API is probably what you would choose if starting from scratch. Where there is already a heavy dependence on callbacks in existing code which you can't or don't want to refactor all at once, then it can get tricky. There's another pattern I use frequently instead, which I find helps.

Although all the various functions remain separate, in their different files, I often use `async.series` or `async.waterfall` as a controller. It means the original functions can be re-used, but it's clear to anyone reading the code that there is a chain of interconnected functions. It allows you to set breakpoints in the controller to follow what's going on, and you don't have to read the code for half an hour to find out how you get to the 10th level down.

There are too few comments in the code currently, which doesn't help either. You can never have too many comments! Within reason, anyway. What's clear to you when initially writing something isn't necessarily going to be clear to someone else. It may not even be clear to you when you come back to it at a later date.

I'm a big believer in simplification and transparency. That includes being brave enough to refactor, if you subsequently discover that the original structure you devised is no longer optimal. A little more development effort, even if it doesn't necessarily add more functionality, can pay dividends for the whole life of the code.

**Pull request merged**
