### PR TITLE
fix: Markdown anchor links in package readMe.md broken #2712

### PR DESCRIPTION
**Pull request by coolsp**
Fixes issue #2712 by replacing all href="# occurrences generated by marker with href="${req.headers.referer}#.
Can't be fixed using baseUrl option from marker as it does not allow a base-URL to be added to an URL starting with #.

### CODE REVIEW

**Review by juanpicado — APPROVED** [review]
LGTM 🥇

**Comment by juanpicado** [comment]
I'll release over the weekend

**Comment by juanpicado** [comment]
Thanks for the smooth PR process 💯 @coolsp !

**Comment by juanpicado** [comment]
I've added a label to port this feature to `master` if you want to contribute to keeping this feat in the next major, also would need to be ported there, for such case is easier all packages are in master, contribution guidelines differ of 5.x a bit, in any case I left the badge we don't forget this in the future.

**Comment by coolsp** [comment]
You're welcome @juanpicado happy to contribute to your hard work !

**Pull request merged**
