### PR TITLE
WIP: Upgrade syntax to ES6 

### PR DESCRIPTION
**Pull request by juanpicado**
This PR migrates syntax to ES6 gradually. Since `verdaccio` supports node v4 as min, it makes totally sense gradually move to the benefits of ES6. It removes shim and pollyfills (Promise and Symbol)

This PR will change several things:

* Code styling
   * `.eslint` less permissive as `eslint-config-google` or `eslint-config-airbnb`
   *  Wrap with **strict mode** due https://github.com/nodejs/node/issues/3318 since we support >Node 4
  * jsDoc document classes
* Replace `async` by es6 features
* Upgrade `logger` colors are based in Octal literals by perhaps either `chalk` or `colors`
* Improve code readability

This will helps (#103 #64 #169) to apply a new plugin system in order switch different storage targets. 

Experimental plugins generators:
Plugin generator: https://github.com/verdaccio/generator-verdaccio-plugin
Auth plugin generated: https://github.com/verdaccio/verdaccio-plugin-auth-htpasswd

### CODE REVIEW

**Comment by juanpicado** [comment]
@Meeeeow could you double check? Resolve those conflicts took a while.

**Comment by Meeeeow** [comment]
I haven't see any conflicts in this PR, i will check later (I'm working now 😆)

**Comment by juanpicado** [comment]
@Meeeeow cool. I've merged already, btw, the `eslint` is yelling like a crazy. I switched errors as warning in order to speed up the merge, but it's n oportunity for a bug fix for anyone that want to contribute.

**Comment by Meeeeow** [comment]
A bit tricky, i will fix some code style when i'm free, but i'll use most time on thinking about new auth plugin

**Pull request merged**
