### PR TITLE
Feat: environment variables support in configuration file

### PR DESCRIPTION
**Pull request by amitgilad3**
add new environment variable VERDACCIO_STORAGE_PATH to allow setting storage not from configuration file #1681

### CODE REVIEW

**Comment by juanpicado** [comment]
I think you would need to rebase rather merge.

**Comment by amitgilad3** [comment]
@juanpicado  - i think this is done - please let me know if i need to add anything else

**Comment by juanpicado** [comment]
thanks for taking care of this, but you might first to clean up the branch, there is 22 commits and most of them are already on master. The ideal before move on the PR only reflect the changes you made. Since you have a fork, I'd recommend fetch the last master and put one commit with your changes on top of it.

**Comment by amitgilad3** [comment]
thanks for the update, i think ill close this pr and create a new one with only the necessary changes

**Pull request closed without merging**
