### PR TITLE
Refactor ui - WIP

### LINKED ISSUE #217: New and modern UI based on React
We want to replace the old UI based on jQuery, there is no ui test, is hard to extend. This will add a new ui based on
* React (ui)
* Jest (test)
* Webpack (build)

Nothing fancy, just a simple UI that replicate the current one, but modern and easy to be tested.

### PR DESCRIPTION
**Pull request by juanpicado**
**Type:** feature

The following has been addressed in the PR:

* There is a related issue: #217 
* Unit or Functional tests are included in the PR

**Description:**

Roadmap: #221

Resolves 

- [x] New and modern UI based on React #217
- [x]  Integrate Webpack to build the UI #218 
- [x] Integrate es6 transpiler like Babel or Typescript #219

### CODE REVIEW

**Comment by Meeeeow** [comment]
I will try implement login feature, then merge it

**Comment by juanpicado** [comment]
Some topics are missing here:
- Dockerfile and Webpack: We need to define how the Dockerfile will handle the pre-build step
- SASS Lint (https://www.npmjs.com/package/stylelint)
- CSS must be minified 
- dot files (.babelrc and any related with webpack should be in root)

**Comment by juanpicado** [comment]
This PR can be tested under `npm install verdaccio@beta -g` beta tag.

**Comment by juanpicado** [comment]
Great job @Meeeeow

**Pull request merged**
