### PR TITLE
fix: path to static directory could be changed

### PR DESCRIPTION
**Pull request by vdakalov**
Fixes path to directory contains static files. It's allows you to change it if client application was build to another directory or client are other application. It would be better to do it differently: I want to specify the path of build backend and client applications, but it impossible do via copy build files from default directory, now its works. But specify path to build client application is impossible now. This PR fixes it problem.

### CODE REVIEW

**Comment by juanpicado** [comment]
@vdakalov thanks for the PR. Could you explain to me what's the issue itself? Mostly for documentation purposes.

**Comment by vdakalov** [comment]
This changes allow you place your client part of application (usually it builtin and named `webui`) into any directory, not only in `./static`. It's may required if you want use own client application or you build webui into another directory. I think it not need specify in documentation, because it not required for normally verdaccio working. Just extends capabillities of verdaccio for DevOps and building scenarios.

**Comment by juanpicado** [comment]
Ah, now I understand 👍 
evaluate

**Comment by juanpicado** [comment]
Thanks @vdakalov nice catch ! Welcome first contribution 🥇

**Comment by vdakalov** [comment]
Thanx guys! I am very glad that I found your project. I'll do my best to help. Now I translate docs to russian language. Already done around 30% :)

**Comment by juanpicado** [comment]
@vdakalov thanks ! I just noticed it 👍 Awesome !

**Pull request merged**
