### PR TITLE
fix: use hasProxyTo to find correct uplink for tarballs

### LINKED ISSUE #1642: Loading upstream tarball doesn't respect package.proxy array
**Describe the bug**

Having multiple uplinks point to the same registry, the package.proxy array gets ignored.
Instead we'll walk through the uplinks and select the last one in the list that can serve the URL we've found for our upstream tarball.

**To Reproduce**

```yml
storage: ./storage

uplinks:
  cachednpm:
    url: https://registry.npmjs.org/
    cache: true
  npmjs:
    url: https://registry.npmjs.org/
    cache: false

packages:
  '**':
    access: $all
    publish:
    proxy: cachednpm
```

1. Run with above config (listening on localhost)
2. Try requesting `http://localhost:4873/@verdaccio/streams/-/streams-8.5.2.tgz`
3. Notice that `./storage/@verdaccio/streams/streams-8.5.2.tgz` does not exist

The uplink chosen here was `npmjs`, not `cachednpm`.

**Expected behavior**

Making the upstream request should respect the packages.proxy array.
In this example, selecting `cachednpm` for it's uplink, causing it to cache the tarball.

**Environment information**

```
Verdaccio version: 4.4.1
System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
```

**Additional context**

I believe the culprit here is:

https://github.com/verdaccio/verdaccio/blob/32aabca6412afdd19a2603205d661f00a667088f/src/lib/storage.ts#L207-L211

The `isUplinkValid` check will be true for both uplinks. So the last one in the array will be selected.
Perhaps it should be using `hasProxyTo` from `src/lib/config-utils.ts`?

### PR DESCRIPTION
**Pull request by Beanow**
Attempting to fix #1642

Reverting the fix commit will fail the test. However I'm not confident we can ignore the `isUplinkValid` check in all situations. The test is also a bit smelly, but can be used as reference.

Feel free to edit as needed.

### CODE REVIEW

**Comment by Beanow** [comment]
Let me know if there's anything you need from me for that :+1:

**Comment by juanpicado** [comment]
There is an interesting variant you should be aware 

```
uplinks:
  cachednpm:
    url: https://registry.npmjs.org/
    cache: true
  npmjs:
    url: https://registry.npmjs.org/
    cache: false

packages:
  '**':
    access: $all
    publish:
    proxy: cachednpm npmjs
```

following your sam example, if there is this scenario, where you can define multiple proxies for one package, the outcome of this would be **no cache** since both proxies will be true and the last one in the list remains, which would be `npmjs`.

If you try
```
  '**':
    access: $all
    publish:
    proxy: npmjs cachednpm
```
switching the `proxy` order, the outcome would be the same. This happens because **the order of definition of uplinks**  matters.

Just keep this on mind.

**Comment by Beanow** [comment]
> clap such a pleasure review this, thanks @Beanow , great stuff.

Glad to hear that :smile: thanks

> There is an interesting variant you should be aware

That _is_ interesting! It's probably best to write some of these scenarios out and agree on what they should do first.

For instance, both `cache: false` and `cache: true` from the same `url`.
Could be considered a config error, because there's no way we could both cache and not cache.
Or it could be considered something we can reduce. So it should cache.

And what about when the urls are different? `cache: true` for yarnpkg but `cache:false` for npmjs on the same package. What should that even do? :thinking:

**Comment by juanpicado** [comment]
Agreed, for now I guess the best is:
- Document the current behavior (website—> uplinks)
- Write more test to prove the current theory 
- Open a discussion how we might handle it better 

It is fue first time someone went so far with the conf :)

**Pull request merged**
