### PR TITLE
Using the env path in the systemd service

### PR DESCRIPTION
**Pull request by metaa**
**Type:** improvement

The following has been addressed in the PR:
* The problem discussed in issue #396

### CODE REVIEW

**Comment by metaa** [comment]
Thanks to @Meeeeow for pointing out this possibility.

**Comment by juanpicado** [comment]
@Meeeeow since I'm not a `windows` guy I have no opinion here :(

**Comment by Meeeeow** [comment]
@juanpicado It's for linux/unix, not Windows

**Comment by juanpicado** [comment]
Sorry, I was thinking in something different. Merging.

**Pull request merged**
