### PR TITLE
fix(ui-theme): show default logo in footer

### PR DESCRIPTION
**Pull request by kuoruan**
The link of the footer logo is verdaccio website, so the logo should be verdaccio's

### CODE REVIEW

**Comment by juanpicado** [comment]
Could you elaborate the problem ? I don't manage to understand.

**Comment by kuoruan** [comment]
@juanpicado I set the logo path in config file to change the banner logo. But the logo in footer also changed.
image

**Comment by juanpicado** [comment]
I have a question for you, why? The footer is meant to display the verdaccio logo with the version, no the brand. I'm not sure if I want this.

**Comment by kuoruan** [comment]
@juanpicado Yes, my change is to show the verdaccio logo in the footer. But the latest version shows the custom brand.

**Comment by juanpicado** [comment]
aaaaaaaaaaaaaaaaaaaaaaaahhhhhhhhhhhhhhhhhhhhhhhhhhh, what you mean is, the current behaviour is we display the logo of the brand on the powered by instead the verdaccio logo, just like this, so you are reporting a bug.

image

Does I get it now correctly?

**Comment by juanpicado** [comment]
In that case, I'd need you add a changeset file, please read here https://github.com/verdaccio/verdaccio/blob/jota/upgrade-deps/CONTRIBUTING.md#adding-a-changeset

**Comment by kuoruan** [comment]
Yes, I think it's a bug, so I made a pull request to fix it.

**Comment by juanpicado** [comment]
> Yes, I think it's a bug, so I made a pull request to fix it.

My apologies, sorry I did get it in the opositive way, let's add the changeset and will be part of the next patch.

**Review by juanpicado — APPROVED** [review]
LGTM

**Comment by juanpicado** [comment]
Thanks @kuoruan

**Pull request merged**
