### PR TITLE
fix running behind of loadbalancer with TLS termination

### PR DESCRIPTION
**Pull request by Vrtak-CZ**
**Type:** bug

The following has been addressed in the PR:

**Description:**

This PR resolves issue when verdaccio is running behind loadbalancer with TLS termination.

### CODE REVIEW

**Comment by juanpicado** [comment]
Nice catch ! Thanks !

**Comment by juanpicado** [comment]
@Vrtak-CZ just curious .. what's a loadbalancer with TLS termination?

**Comment by Vrtak-CZ** [comment]
@juanpicado loadbalancer where HTTPS (TLS connectin - SSL is obsolete and unsecure) terminates encrypted connection (User -> LoadBalancer (https://) -> Server (http://)).

**Comment by kgrubb** [comment]
Basically, the load balancer is where all of the ssl/tls is managed and vetted, then behind the load balancer (now that things have been authorized), everything is unencrypted.

**Comment by juanpicado** [comment]
Ahh I see !! Thanks guys. You will laugh ... but I read TLS 😆  .. I was thinking on Node LTS and so on ..... I need a coffee now.

**Pull request merged**
