### PR TITLE
fix: no longer throws exception upon a field-specific query

### PR DESCRIPTION
**Pull request by brianblakely**
Search wrapped all database queries in wildcards, which broke field queries and caused Verdaccio to throw a 500 when one was attempted.  This merge identifies field queries and subsequently omits the wildcard wrapper.

### CODE REVIEW

**Comment by juanpicado** [comment]
> Search wrapped all database queries in wildcards, which broke field queries and caused Verdaccio to throw a 500 when one was attempted. This merge identifies field queries and subsequently omits the wildcard wrapper.

could you provide a reproducible steps?

**Comment by brianblakely** [comment]
> could you provide a reproducible steps?

Certainly, you just need to make a GET against the search API while using a Lunr field query.

1. Run Verdaccio
2. Perform a GET against the API, for example with curl:
`curl http://localhost:4873/-/verdaccio/search/keywords:foo`

Pre-merge, Verdacccio will throw 500.  Post-merge, Lunr will perform the query.

**Review by juanpicado — CHANGES_REQUESTED** [review]
Looks pretty handy, but when I query a non field eg: `name1:verdaccio` the server crash. I'd suggest try catch and return empty in the worse case.
```
 http <-- 500, user: null(127.0.0.1), req: 'GET /-/verdaccio/search/%3Aname', error: internal server error
req.params.anything :name
 error--- unexpected error: unrecognised field '', possible fields: 'name', 'description', 'author', 'keywords', 'version', 'readme'
````

**Comment by juanpicado** [comment]
`lunr-mutable-indexes` does not longer exist on master, I'll close this, thanks anyway.

**Pull request closed without merging**
