### PR TITLE
feat: allow overwriting existing package when publishing

### LINKED ISSUE #1402: Forcibly republish the package with the same version
**Is your feature request related to a problem? Please describe.**
Let's have a situation that I want to keep my package version in sync with other software. I.e.: my-dto:1.2.3, other-software:1.2.3. The problem that I have is once I publish the package I can't easily unpublish it nor forcibly update it. The question is: Is there any way to forcibly republish the package in my private verdaccio instance with the same version?

**Describe the solution you'd like**
I want to be able to forcibly update the package which has already been published.

**Describe alternatives you've considered**
or at least be able to unpublish it quickly and then publish it again, so I don't need to remove entries from the database to erase old package.

**Additional context**

- I stripped fragile data with XXX.
- My Verdaccio version: 3.11.4

1. The package is already published by in my registry under `https://npm.XXX.systems/@my-dto`

```
yarn publish --registry=https://npm.XXX.systems
yarn publish v1.17.3
[1/4] Bumping version...
info Current version: 9.4.0
question New version: 9.4.0
[2/4] Logging in...
[3/4] Publishing...
error Couldn't publish package: "https://npm.XXX.systems/@my%2fdto: this package is already present"
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

### PR DESCRIPTION
**Pull request by mbtools**
You can now allow overwriting a package (tarball) that is already in the local registry.

```yaml
publish:
  allow_overwrite: true
```

Closes #1402

Todo:

- [ ] update default config.yaml
- [ ] update docs

### CODE REVIEW

**Comment by juanpicado** [comment]
Regarding this, I'm thinking the same as https://github.com/verdaccio/verdaccio/issues/1402#issuecomment-2505419797 I think this might require more investigation, the feature might be misused easily. 

I am still with the idea https://github.com/verdaccio/verdaccio/issues/1402#issuecomment-544190898 if this behaviour is allowed, should be on a clean storage every time the app runs, intended for E2E or quick usage, not for longer term registry.

**Comment by mbtools** [comment]
I agree. The point of a registry is to guarantee that a version can't be changed, so this is not for productive use. Checking for NODE_ENV <> production makes sense. Or maybe we explicitly check for NODE_ENV = ci

**Comment by juanpicado** [comment]
> I agree. The point of a registry is to guarantee that a version can't be changed, so this is not for productive use. Checking for NODE_ENV <> production makes sense. Or maybe we explicitly check for NODE_ENV = ci
> 
> 
> 
> 

I would prefer something less standard because some pipelines might use that already for other reasons, each env variable in verdaccio is prefixed with VERDACCIO_xxx so we might enable dev mode at the config package via that variable only and display clear warnings the mode was enabled and then use this property in the same way you are already using the one you purposed. It should requires a new empty storage, it could use the same location that the default storage is create but with a generated name like the current e2e test.

**Comment by mbtools** [comment]
- Switched to `VERDACCIO_DEV_MODE === 'allow_overwrite'`
- Added check for empty storage at init
- Warning message if overwrite mode is enabled

**Comment by eldoy** [comment]
Why not just make `npm publish --force` work? We don't need guardrails against ourselves.

**Comment by mbtools** [comment]
That would be nice but [`npm publish`](https://docs.npmjs.com/cli/v10/commands/npm-publish) does not have a `--force` switch.

**Comment by juanpicado** [comment]
fyi: I've rebased, (resolved conflicts)

**Review by juanpicado — COMMENTED** [review]
@mbtools I've been reviewing this but I think still there is room for improvement  here:
- The necessity to provide a custom storage every time it is a bit misleading, while trying to publish I had to manually remove the storage. I suggest the registry creates a separated sandbox that can be used only once, do not mix with the current storage to avoid the `if/else` is at the storage.
- Overwrite a package happens as expected, but the feedback still not enough. We might need to be more prominent, to avoid misuses of this feature.
- I'd recommend tag it as experimental, this allows breaking changes anytime easily. 
- The dev mode could be many things in the future, not sure how to picture this in a better way, anyhow running `VERDACCIO_DEV_MODE=allow_overwrite verdaccio` still feels like can do only one thing. 
- I tried to publish and install the dependency in another local project but besides the integrity check changes, I never got any integrity error or warning 💭 🤷🏼‍♂️ 

Maybe you can rebase, seems some code was connected with other PR I already merged.


... and happy new year 🥳

**Comment by mbtools** [comment]
I cleaned up the PR. I agree that 
- this should be experimental
- dev mode isn't generic enough
- it needs more testing on how npm/pnpm/yarn behaves if an existing package is changed

Since npm doesn't allow republishing a version, the client might not check the integrity correctly. That would be bad since man-in-the-middle could inject a different package. 😱 

I won't have time to work on this for some months. We will have this as a reference. If someone needs it, they can apply the changes to their fork.

**Comment by eldoy** [comment]
You can also just delete the package you want to republish from `/verdaccio/storage` and then publish again, solves the problem for me.

**Comment by mbtools** [comment]
Sure, @eldoy, but it's manual and you need access to the storage. The goal is to get something that works in automated CI scenarios.

**Comment by eldoy** [comment]
Scripted/automated through SSH: `ssh server "rm -rf /verdaccio/storage/@eldoy/pkgname"`

**Pull request closed without merging**
