### PR TITLE
chore(crowdin): custom conventional commit message

### PR DESCRIPTION
**Pull request by bufferoverflow**

### CODE REVIEW

**Comment by juanpicado** [comment]
You are my hero 🥇 . Good catch

**Comment by juanpicado** [comment]
😢 it does not seem to work 

```
commit_message: 'docs(website): new translations'
```

**Comment by bufferoverflow** [comment]
😢 maybe a caching topic on crowdin or not really an option?

**Comment by juanpicado** [comment]
I'll ask support, in the meantime I'll `squash and merge`

**Pull request merged**
