### PR TITLE
feat: S3 tokens functionality

### PR DESCRIPTION
**Pull request by niki-timofe**

### CODE REVIEW

**Comment by juanpicado** [comment]
hi @niki-timofe thanks for this PR, some comments.

I wonder if you want to use this feature right away this is the wrong place to PR , should be here

https://github.com/verdaccio/monorepo/tree/9.x/plugins

For this version, I could merge, but not sure how useful might be for you since https://github.com/verdaccio/verdaccio/pull/2218 will basically rewrite all of it eventually.

**Comment by manast** [comment]
I need this feature, I can finalize it but I wonder, will it be released in the 5.x branch?

**Comment by juanpicado** [comment]
If you want it for `5.x` then has to be ported here https://github.com/verdaccio/monorepo/tree/9.x/plugins (I won't do because I'm not focused on adding new features on 5.x but I'll be happy to help to merge/review if others do instead 👍🏼 ). 

Furthermore @leometzger is migrating to v3 https://github.com/verdaccio/verdaccio/pull/2574 so this PR might be outdated soon or later.

**Comment by manast** [comment]
> Furthermore @leometzger is migrating to v3 #2574 so this PR might be outdated soon or later.

AFAICS that PR does not add token support. So if we merge this, then if the v3 migratio.n is merged before we can port it easily. I want to get this ready ASAP so probably is ready before #2574.

Anyway, it seems that easiest is to first merge into verdaccion:master to whatever release that may become and then backport to the v5, mainly because this PR is almost ready.

**Comment by juanpicado** [comment]
As you wish, I have no issues to merge this when is ready. But I cannot guarantee a fast release and stable package, the master branch is `alpha`.

If you want it fast, then https://github.com/verdaccio/monorepo/tree/9.x/plugins is the way to go, but again, as you wish.

**Pull request closed without merging**
