### PR TITLE
refactor: remove extraneous else statements

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**
refactor

The following has been addressed in the PR:

*  There is a related issue?
*  Unit or Functional tests are included in the PR

**Description:**

This PR removes extraneous / unnecessary `else` statements.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hm, it seems some linting errors / warnings are thrown on GH Actions now.

Can you check that @juanpicado?

**Comment by juanpicado** [comment]
@DanielRuf usual warnings we need to clean up, but it has been there for a while, harmful

**Comment by DanielRuf** [comment]
Ah, because there not yellow anymore. I thought it was due to my changes. I guess this is because only changed files are checked, right?

**Comment by juanpicado** [comment]
> I guess this is because only changed files are checked, right?

It might be, let's see on master after merge this.

**Pull request merged**
