### PR TITLE
Allow HTTP Agent options to be configured for uplink

### PR DESCRIPTION
**Pull request by willsmythe**
**Type:** feature

This allows [HTTP Agent options](https://nodejs.org/api/http.html#http_new_agent_options) to be configured for an uplink. This gives users control over settings like [maxSockets](https://nodejs.org/api/http.html#http_new_agent_options) (controls the maximum number of sockets that can be open/created for a host), which is important in certain environments. See #1329 for one example.

Any options set via a new `agent_otions` uplink configuration option are passed directly through to `request`, which combines them with other options to create an HTTP Agent (or reuse an existing agent if one with the same configuration already exists in the pool). See [request.js#L698](https://github.com/request/request/blob/df346d8531ac4b8c360df301f228d5767d0e374e/request.js#L698)

Example configuration with agent_options:

```yaml
uplinks:
  npmjs:	  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 40
    maxage: 30m
    timeout: 60s
    agent_options:   /* customizes HTTP agent options for connections between Verdaccio and the upink */
      keepAlive: true
      maxSockets: 40
      maxFreeSockets: 10
```
**Description:**

See #1329

### CODE REVIEW

**Comment by willsmythe** [comment]
Before I fix the lint, etc build problems, can someone on the project review the general approach being proposed here? 

Main question in my mind: should there be a stricter contract for "agent_options"? Right now the user can pass any object, which will get merged with other options by `request` when it creates an HTTP/HTTPS agent.

Not having a fixed contract for "agent_options" makes sense in some ways since different agent classes could [theoretically] be used by `request` (although request will likely use the Node `http.Agent` or `https.Agent` since Verdaccio doesn't set the `agent` or` agentClass` request options). However, in reality one of the two agent classes will be used, and each of these has a fixed set of options (see for [http.Agent](https://nodejs.org/api/http.html#http_new_agent_options) and for [https.Agent](https://nodejs.org/api/https.html#https_new_agent_options)).

**Comment by juanpicado** [comment]
I'm fine with not having a fixed contract for "agent_options", you have my 👍

**Comment by juanpicado** [comment]
@willsmythe be aware I updated the base to the branch `4.1.x`, since this, a feature and should be included in the next minor release.

**Comment by willsmythe** [comment]
@juanpicado - cool. Let me retest off this new base. Assuming this gets merged in the next few days, will it make the next minor release? And when is the next minor release (approximately)?

@ianschmitz - FYI

**Comment by juanpicado** [comment]
@wiggisser I usually set dates here https://github.com/verdaccio/verdaccio/milestones for each milestone (that might depend on available resources), the rule is simple, whatever is ready for release, goes in, otherwise, wait for the next minor release (1 per month).

**Comment by willsmythe** [comment]
@juanpicado - thanks. Btw, I didn't see any docs/guidance about updating @verdaccio/types. My main question: what branch should I target a PR against and what is the general process for consuming an updated version in verdaccio/verdaccio?

**Comment by juanpicado** [comment]
`4.1.x` still uses https://github.com/verdaccio/verdaccio/blob/4.1.x/package.json#L55 `5.0.2` so https://github.com/verdaccio/flow-types/tree/5.x branch.

Type repo is really hard to handle, so many features ongoing, but `5.x` is safe. The guide for typings still needs to be done but depends of https://github.com/verdaccio/verdaccio/issues/1166 , I guess soon I'll put an order in that repo :-)

**Comment by ianschmitz** [comment]
Hey @juanpicado. Any progress or thoughts on this? We're hoping to bring create-react-app up to date with Verdaccio but i think this is the last remaining piece.

Thanks!

**Comment by juanpicado** [comment]
Actually I was waiting @willsmythe to resolve the conflict. But I'll do it myself in a new PR.

**Comment by juanpicado** [comment]
@ianschmitz you should be able to test wit `verdaccio@4.3.3`.  Let me know if you need something else. 👍

**Pull request closed without merging**
