### PR TITLE
fix: fix the exact search phrase

### LINKED ISSUE #1632: Bug: exact search phrase does not work
**Describe the bug**
When searching for `jquer` the search API correctly returns `jquery`. If we input `jquery` it returns an empty array and so the search suggestions are also empty in the UI.

**To Reproduce**
Search for `jquery` and `jquery`. See the responses in the network tab.

1. Go to verdaccio frontend
1. Input `jquer`
1. Check results
1. Input `jquery`
1. Check results

**Expected behavior**
A direct match should return the packages.

**Screenshots**

Bildschirmfoto 2019-12-25 um 15 39 55

Bildschirmfoto 2019-12-25 um 15 39 46

### PR DESCRIPTION
**Pull request by leometzger**
Hello, this PR resolves #1632 

**Description**
In order to resolve the issue, I used the workaround [olivernn/lunr.js#38](https://github.com/olivernn/lunr.js/issues/38) that remove the stemmer from index.

### CODE REVIEW

**Comment by juanpicado** [comment]
One test is failing, maybe you want to look into that. If you need help let me know

**Comment by leometzger** [comment]
Thanks. 

The test was fixed. I also added a new test for the opposite situation.

Apparently it is all passing now.

**Review by juanpicado — DISMISSED** [review]
Great job !

Could you add a changeset ?https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#adding-a-changeset

**Comment by leometzger** [comment]
Sure. Changeset added.

Next time I add from beggining ^^

**Review by juanpicado — APPROVED** [review]

**Comment by wuliupo** [comment]
Which version of Verdaccio will fix this bug?

**Comment by juanpicado** [comment]
@wuliupo `npm install --global verdaccio@6-next` but nothing that is stable, I won't recommend use v6 by now, it is quite broken in few places. Release is not close, maybe next year, a lot of refactoring going on.

**Pull request merged**
