### PR TITLE
Add missing octokit/rest package for the trigger-release script

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**

The following has been addressed in the PR:

*  CI release script fails due to missing `octokit/rest` package. This PR adds it.

**Description:**

### CODE REVIEW

**Comment by juanpicado** [comment]
Hi ! 🤔 ... could you give me more context?

**Comment by DanielRuf** [comment]
Sure, see the current CI status and https://github.com/verdaccio/verdaccio/runs/113213375

**Comment by juanpicado** [comment]
@DanielRuf we forgot to update the lock file, no worries. I did it already.

**Comment by DanielRuf** [comment]
> we forgot to update the lock file, no worries. I did it already.

Not sure what you mean. Only the person who controls the master branch should update the lockfile (security and conflict reasons) ;-)

**Comment by juanpicado** [comment]
Well, we run the CI with `--frozen-lockfile` thus, fails. But for some reason, the GH Actions are not running on PRs. So I did not realised.

**Comment by ayusharma** [comment]
Yes, I forgot to add the octokit deps. Thanks @DanielRuf 😃

**Pull request merged**
