### PR TITLE
Change the way package distribution tags are processed and stored

### PR DESCRIPTION
**Pull request by steve-p-com**
Changed the way package distribution tags are processed and stored to replicate more closely the behaviour of the upstream repository (npmjs.org).

### CODE REVIEW

**Comment by steve-p-com** [comment]
Once last time (I hope)!

The only two failures now are the race condition tests.

**Comment by trentearl** [comment]
I was about to merge but noticed that you included `package.yaml` changes in this merge request as well. Was that on purpose?

I like both of these changes, but I think they should be in two different PRs/commits

**Comment by steve-p-com** [comment]
No it wasn't. I wasn't sure how this merge would be impacted by a subsequent unrelated commit. Now I know! It's only the first commit that's relevant. Let me reverse that one and see what happens.

**Comment by steve-p-com** [comment]
OK that's on its own again now. I've got the WIP changes for the other stuff back as uncommitted modifications on my local copy.

**Comment by trentearl** [comment]
Thanks for this! @steve-p-com  👍

**Comment by juanpicado** [comment]
This is causing https://github.com/verdaccio/verdaccio/issues/702 🐞

**Pull request merged**
