### PR TITLE
To fix NewRelic issue

### LINKED ISSUE #884: NewRelic Agent throwing errors after update to 3.3.0 version
**Describe the bug**
NewRelic Agent throwing errors after update to 3.3.0 version. 
Error is following:
```
{"v":0,"level":50,"name":"newrelic","hostname":"5538dce32c23","pid":75,"time":"2018-08-01T14:20:12.118Z","msg":"Unable to serialize payload for method connect.","component":"remote_method","stack":"TypeError: this is not a Date object.\n    at Object.valueOf (<anonymous>)\n    at Object.[Symbol.toPrimitive] (<anonymous>)\n    at Object.toJSON (<anonymous>)\n    at JSON.stringify (<anonymous>)\n    at stringify (/www/docker/node_modules/json-stringify-safe/stringify.js:5:15)\n    at RemoteMethod.serialize (/www/docker/node_modules/newrelic/lib/collector/remote-method.js:42:15)\n    at RemoteMethod.call [as invoke] (/www/docker/node_modules/newrelic/lib/collector/remote-method.js:64:8)\n    at CollectorAPI._connect (/www/docker/node_modules/newrelic/lib/collector/api.js:186:21)\n    at getEnvDict (/www/docker/node_modules/newrelic/lib/collector/api.js:178:10)\n    at factMapCb (/www/docker/node_modules/newrelic/lib/collector/facts.js:67:12)","message":"this is not a Date object."}
```

As result - empty NewRelic logs

**After some investigation**

After some investigation in diffs:
https://github.com/verdaccio/verdaccio/compare/v3.2.0...v3.3.0
I've found a PR https://github.com/verdaccio/verdaccio/pull/764. 
After that PR merge it breaks NewRelic logic.

It works well after the commit https://github.com/verdaccio/verdaccio/commit/825f5a57eaa04a895fbf9673481fcf647b0a0d68

But after the https://github.com/verdaccio/verdaccio/commit/29bb57ad5f5d762e8f1f4e3267f5bd11f8caa272 commit it is broken.

**Screenshots**

comparing_v3_2_0___v3_3_0_ _verdaccio_verdaccio

### PR DESCRIPTION
**Pull request by aremishevsky**
**Description:**

Seams like i've found a solution - could you please update "asciidoctor.js" package to the latest "1.5.7-rc.1" version? (it already includes the "opal-runtime" latest 1.0.7 version)
https://www.npmjs.com/package/asciidoctor.js?activeTab=versions

Current 1.5.6 version of "asciidoctor.js" requires only "1.0.3" version of the "opal-runtime" module.

I've changed it manually in the verdaccio's package.json, rebuilt it and newRelic become alive.)))

Resolves #884

### CODE REVIEW

**Comment by juanpicado** [comment]
@aremishevsky please provide some context. 

For some reason CircleCI is failing only in PR, we need to fix that first before the merge.

**Comment by aremishevsky** [comment]
@juanpicado ok then.
Please let me know once it would be fixed...

**Comment by juanpicado** [comment]
I meant, https://github.com/verdaccio/verdaccio/issues/884#issuecomment-414739839 should be the description on this PR. I just pasted here.

**Comment by aremishevsky** [comment]
@juanpicado should I commit something to re-trigger builds?

**Comment by juanpicado** [comment]
@aremishevsky I think is related with https://circleci.com/blog/sunsetting-1-0/
@sergiohgz I don't know whether he has more context.

**Comment by aremishevsky** [comment]
@juanpicado does all your PRs are blocked with these builds?
Or just mine?

**Comment by juanpicado** [comment]
@aremishevsky no, just a hassle because we have no feedback from circle cli. No worries I'll handle it.

**Comment by aremishevsky** [comment]
@juanpicado hmmmm. it's very strange.
I've ran `yarn test` command and i've got:
```
Test Suites: 46 passed, 46 total
Tests:       3 skipped, 314 passed, 317 total
Snapshots:   31 passed, 31 total
Time:        14.632s, estimated 23s
Ran all test suites.
✨  Done in 18.88s.
```
I've tried `npm run test:unit` command. Got the same result.

Maybe you've meant "test:functional" (not unit)?

**Comment by aremishevsky** [comment]
@juanpicado I've found an interesting thing:
if you do:
```
yarn install --production=false && yarn lint && yarn code:build && yarn build:webui && yarn cache clean
npm run test:functional
```
you will get:
```
Test Suites: 1 failed, 1 total
Tests:       5 failed, 148 passed, 153 total
Snapshots:   0 total
Time:        10.63s, estimated 12s
```

However if you do:
```
npm install
npm run test:functional
```
you will get:
```
Test Suites: 1 passed, 1 total
Tests:       153 passed, 153 total
Snapshots:   0 total
Time:        11.314s
```

How this could be possible?

**Comment by ayusharma** [comment]
All test are passing for me as well.

**Comment by ayusharma** [comment]
functional test are failing. @juanpicado we can not have this change until we figure out issues with asciidoctor and our tests.

```
yarn run test:all
```

**Comment by aremishevsky** [comment]
After some investigation I've found that our tests and a NewRelic agent works correctly ONLY with "opal-runtime" 1.0.6 version - which is not included in any of release version of asciidoctor.js package.
asciidoctor.js 1.5.6 - opal-runtime 1.0.3 (broken NewRelic)
asciidoctor.js 1.5.7-rc.1 - opal-runtime 1.0.7 (broken Handlebars)

Only after the manual setup of the 1.0.6 opal-runtime it became to the normal work.

@juanpicado @ayusharma do we have some alternatives to use some other module instead of "asciidoctor.js"? 
It breaks global JS prototyped context from version to version in the different places.

If not - I will log a ticket for "asciidoctor.js" and link it here.

**Comment by juanpicado** [comment]
> Only after the manual setup of the 1.0.6 opal-runtime it became to the normal work.

Could you explain me that part?

**Comment by juanpicado** [comment]
> do we have some alternatives to use some other module instead of "asciidoctor.js"?

We weel need to research. But if `asciidoctor.js` affects other libraries due to monkey patching ... we have to reconsider to having it.

**Comment by ayusharma** [comment]
@aremishevsky Thank you so much for the detailed research on this issue. 

@juanpicado I do not see any alternative to asciidoctor. We can deprecate this feature. (Complete removal of ascii support.)

Please let me know your thoughts on this.

**Comment by juanpicado** [comment]
@aremishevsky after having a chat with @ayusharma we decided to remove `asciidoctor`. He will PR and next `3.x` version will be free of it. I'll close this PR for now. Thanks for your research that will avoid future issues with other dependencies.

**Comment by aremishevsky** [comment]
@juanpicado @ayusharma thanks!!!
This would prevent a lot of errors!

**Pull request closed without merging**
