### PR TITLE
Fl4re rebased

### PR DESCRIPTION
**Pull request by trentearl**
This PR is a rebase of https://github.com/fl4re/sinopia

Fixes: #15

### CODE REVIEW

**Comment by nwhite89** [comment]
👍

**Comment by Meeeeow** [comment]
Why this PR is not merged?

BTW: Commit 364fbdcfaf9130a9c7f69d043e975ec3cfe18aca may include breaking change

The author says he removed hard coded host and port, but variable `baseUrl` is not hard coded,  it read `url_prefix` from config file, if not set, it will use host and port from request.

After remove it, if someone install it on `https://example.org/verdaccio/` with reverse proxy will cause 404 error, and `url_prefix` will not work anymore

**Comment by juanpicado** [comment]
@Meeeeow I'd close this PR and spit them up in separated PR. Some commits here either hve been already merged by previous PR or don't make sense anymore . eg: https://github.com/verdaccio/verdaccio/pull/17/commits/ab40c91f820e97b666ca6351ff8317f4ad06a077 would be a mess merge that one. I really suggest if you considere worth merge https://github.com/verdaccio/verdaccio/commit/364fbdcfaf9130a9c7f69d043e975ec3cfe18aca please fill a separate PR.

**Comment by Meeeeow** [comment]
No, i mean commit 364fbdcfaf9130a9c7f69d043e975ec3cfe18aca should NOT merge.
I will create PRs if i can fix some bugs or any feature

**Comment by juanpicado** [comment]
@Meeeeow sorry I misread your comment (It's too early here ☕ ) . I'd appreciate that. Thanks.

**Comment by juanpicado** [comment]
I'll close this one, the follow up is #163

**Pull request closed without merging**
