### PR TITLE
feat: migrate yarn workspaces

### PR DESCRIPTION
**Pull request by juanpicado**
**Type:** feat

**Description:**

## Context

Verdaccio has been traditionally a single package web application that has been evolve to achieve new features along the last 3 major releases, as the  *Storage API*, Node API and new set of plugins. We have increased the set of test in order to provide a really stable experience. 

Unfortunately the current architecture is not easy to scale and is time to move on. Early last year we decided to experiment with [monorepo](https://github.com/verdaccio/monorepo) and move there plugins, business logic that is essential for plugin development and stack tooling to provide a good base to start to build plugins, the outcome has been more than positive and the next step is move **core** to the same approach.

Verdaccio 5 will be monorepo by design, using workspaces with lerna + yarn (at this stage is the best option of migration due the internal experience we own), but I don't throw the idea to use [pnpm](https://github.com/pnpm/pnpm) as base of our monorepo , since is one tool instead two, time will tell.

### What's new?
- Verdaccio 5 (at this stage) still fully compatible with previous versions, but along the alphas are being shipped breaking changes will arrive, specially for plugins (since is the hotspot for enhancement request)
- Unit testing structured completely refactored
- Separation of concerns (each package will own set of test, no more mixed unit test)
- Update dependencies issues are fixed (eg: we were not able to update `request` due issues with our testing pipeline) 
- We open the door for new features, as hooks (before named notifications) which we plan to increase it power along the next alphas being able to notify more actions (currently only publishing)
- Logging: We have been using `bunyan` but we have plans migrate to #1334 either PinoJS or being able to use a different logging system.
- Scoped packages: We want to scope all packages, even the core, but will be available from the original source but will have an scoped alias, eg: `@verdaccio/cli`

... and many more things which will depends of the available human resources.

### This PR

I'm limiting this PR to migrate to lerna and yarn workspaces, no app logic or testing refactoring is being done, just relocate and refactor the build stack, so the outcome of this PR would be like use the latest Verdaccio 4 without any significant modification for user and plugins developers.

> I'm constantly rebasing from `master` so this PR does not get outdated.

## Quick todo list

- [x] Prepare project for usage of workspaces. 
- [x] Setup lerna
- [x] Create new modules
- [x] Fix lints
- [x] Fix scripts
- [x] Fix tests
- [x] Fix deployments
- [x] Fix Release pipeline
- [x] Prepare Docker image (+ deployment)

## Deployments

Trial using the GitHub registry
```
https://github.com/verdaccio/verdaccio/packages
```

Current canary is being deployed in our registry via:

```
npm i -g @verdaccio/cli@canary --registry https://registry.verdaccio.org
```
or
```
npm i -g verdaccio@canary --registry https://registry.verdaccio.org
```

> `verdaccio@canary` is just a wrapper of `@verdaccio/cli@canary` which is exactly the same

Website: https://registry.verdaccio.org/-/web/detail/@verdaccio/cli

### CODE REVIEW

**Comment by sergiohgz** [comment]
:gold_medal: Awesome work, still draft, but it's time to evolve

**Comment by sergiohgz** [comment]
@juanpicado let me know if you need help with some work :wink:

**Comment by juanpicado** [comment]
I will your help with the deployment for sure, you have way more experience 🙏

**Comment by juanpicado** [comment]
Currently I am working on migrate unit test peer package (huge task) and refactoring configuration to make much easier to understand, but none tests is being modified or any logic, just moving stuff around and config files.

**Comment by juanpicado** [comment]
@sergiohgz @DanielRuf  I don't get the error
```
console.error ../../node_modules/jest-jasmine2/build/jasmine/Env.js:290
@verdaccio/server:     Error: EACCES: permission denied, mkdtemp '/tmpXXXXXX'
```
😢

**Comment by juanpicado** [comment]
Well ... took me 2 months, but I did it, this is being merged on `5.x` and then tackle more stuff from there.  

```
 docker run -it --rm -p 4873:4873 verdaccio/verdaccio:5.x-next
```
or
```
npm i -g verdaccio@canary --registry https://registry.verdaccio.org
```

**Pull request merged**
