### PR TITLE
feat: docker image bump to node.js 10.16

### PR DESCRIPTION
**Pull request by juanpicado**
**Type:** feat

**Description:**

Update Docker to Node.js 10.16

### CODE REVIEW

**Comment by sergiohgz** [comment]
We really want to use Node 10 as base image or do we want to update to Node 12?

**Comment by juanpicado** [comment]
@sergiohgz we use LTS by default. At least at this moment only Node.js 10 is LTS
https://nodejs.org/en/about/releases/
but we can move to Node.js in future releases I guess.

**Comment by sergiohgz** [comment]
Perfect 👌 Node 8 is still LTS but it's near it's end, so really great ☺

**Comment by juanpicado** [comment]
With Node 8 out of the field and Node.js 12 as default LTS for us, we will be able to transpile more efficiently.

**Pull request merged**
