### PR TITLE
new search command compatible with npm search

### PR DESCRIPTION
**Pull request by pascalStm**
Hello,

I added the search command to be compatible with the search command of npm, for now I'm only processing one term for search.
With this command we can retrieve the result of the search in json with the command npm-search.

Thank you
```
example:  npm search --json @verdaccio
result:
[{"name":"@verdaccio/local-storage","description":"local storage implementation","maintainers":[{"username":"jotadeveloper","email":"juanpicado19@gmail.com"}],"keywords":["verdaccio","local-storage"],"version":"0.0.11","date":"2017-10-22T08:44:45.906Z"}
,{"name":"@verdaccio/streams","description":"helper to delay streams","maintainers":[{"username":"jotadeveloper","email":"juanpicado19@gmail.com"}],"keywords":["streams"],"version":"0.0.2","date":"2017-08-02T05:33:34.992Z"}
,{"name":"@verdaccio/types","description":"verdaccio flow types definitions","maintainers":[{"username":"jotadeveloper","email":"juanpicado19@gmail.com"}],"version":"0.0.9","date":"2017-11-22T06:00:57.589Z"}
,{"name":"@verdaccio/file-locking","description":"library that handle file locking","maintainers":[{"username":"jotadeveloper","email":"juanpicado19@gmail.com"}],"keywords":["lock","fs"],"version":"0.0.3","date":"2017-07-08T14:07:19.907Z"}
]
```

### CODE REVIEW

**Comment by juanpicado** [comment]
Sorry, in order to release I need you update (https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#git-commit-guidelines) commit messages. We have an automated process, otherwise, the CI won't do the release.

**Comment by juanpicado** [comment]
Could you update as well this section? https://github.com/verdaccio/verdaccio/blob/master/README.md#compatibility

**Comment by juanpicado** [comment]
Please review the lint, it fails 
```
> verdaccio@2.7.0 lint /home/ubuntu/verdaccio
> eslint .


/home/ubuntu/verdaccio/src/api/endpoint/api/search.js
   99:1    warning  Trailing spaces not allowed                                                                                 no-trailing-spaces
  100:3    error    Expected space or tab after '//' in comment                                                                 spaced-comment
  132:1    warning  Trailing spaces not allowed                                                                                 no-trailing-spaces
  158:90   error    Missing semicolon                                                                                           semi
  159:11   error    Expected { after 'if' condition                                                                             curly
  159:95   warning  Trailing spaces not allowed                                                                                 no-trailing-spaces
  160:2    warning  Mixed spaces and tabs                                                                                       no-mixed-spaces-and-tabs
  160:12   error    The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype  guard-for-in
  160:134  error    Missing semicolon                                                                                           semi
  163:11   error    Opening curly brace does not appear on the same line as controlling statement                               brace-style
  166:1    warning  Line 166 exceeds the maximum line length of 160                                                             max-len
  166:4    error    Expected space or tab after '//' in comment                                                                 spaced-comment
  189:1    error    Missing JSDoc comment                                                                                       require-jsdoc
  189:24   error    Unexpected space before function parentheses                                                                space-before-function-paren
  193:55   error    Unexpected space before function parentheses                                                                space-before-function-paren
  194:14   error    There should be no space after '{'                                                                          object-curly-spacing
  194:49   error    There should be no space before '}'                                                                         object-curly-spacing
  194:50   error    Missing semicolon                                                                                           semi
  202:14   error    Missing trailing comma                                                                                      comma-dangle
  203:4    error    Missing semicolon                                                                                           semi

/home/ubuntu/verdaccio/src/utils/string.js
  2:21  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params

✖ 21 problems (15 errors, 6 warnings)
````

**Comment by juanpicado** [comment]
Does work for you? It does not for me.

```
➜ npm search jquery --json --registry http://localhost:5555 -dd
npm info it worked if it ends with ok
npm verb cli [ '/Users/user/.nvm/versions/node/v8.7.0/bin/node',
npm verb cli   '/Users/user/.nvm/versions/node/v8.7.0/bin/npm',
npm verb cli   'search',
npm verb cli   'jquery',
npm verb cli   '--json',
npm verb cli   '--registry',
npm verb cli   'http://localhost:5555',
npm verb cli   '-dd' ]
npm info using npm@5.5.1
npm info using node@v8.7.0
npm verb esearch creating remote entry stream
npm verb request uri http://localhost:5555/-/v1/search?text=jquery&size=20
npm verb request no auth needed
npm info attempt registry request try #1 at 22:18:26
npm verb request using bearer token for auth
npm verb request id 02d6cd49fe2dfb3f
npm http request GET http://localhost:5555/-/v1/search?text=jquery&size=20
[
]
npm verb exit [ 0, true ]
npm info ok 
```

**Comment by pascalStm** [comment]
yes, the search only works on packages that have been published in the server npm verdaccio, it does not launch the search commands on packages that is published in other server npm for example: "https: //registry.npmjs. org /. "

**Comment by pascalStm** [comment]
yes, the search only works on packages that have been published in the server npm verdaccio, it does not launch the search commands on packages that is published in other server npm for example: "https: //registry.npmjs. org /. "

**Pull request closed without merging**
