### PR TITLE
feat: ensure every log file has at least one record

### PR DESCRIPTION
**Pull request by mlucool**
**Type:** feature 

The following has been addressed in the PR:
**Description:**
Sometimes logs are empty if no one tries to access verdaccio. This is especially with logrotate where no one may access it over a period of time. This commit ensures every log has at least one message in it (assuming `warn` or above level of logging).

### CODE REVIEW

**Comment by juanpicado** [comment]
I will check it later,  but, I am rethinking about file rotation in the next major release next year and remove such support. Thoughts ?

**Comment by mlucool** [comment]
Why would you want to remove that? IMO, it's a great and useful feature!

This issue comes up without file rotate also, hence the `Verdaccio started` log statement.

**Comment by juanpicado** [comment]
There is a issue, the message get printed twice on startup with the default config.

**Comment by mlucool** [comment]
> There is a issue, the message get printed twice on startup with the default config.

Not sure if that's a bug. The issue is that in the default logging, we call setup twice and both happen to output to the same place (console). First in `cli.ts` then in `index.ts`. In theory these are different logs. I can add something to make `cli.js` not add this output if you think that's cleaner.

**Comment by juanpicado** [comment]
> Not sure if that's a bug. The issue is that in the default logging, we call setup twice and both happen to output to the same place (console). First in `cli.ts` then in `index.ts`. In theory these are different logs. I can add something to make `cli.js` not add this output if you think that's cleaner.

It is a design decision by my predecesor. Since we have this in in progress https://github.com/verdaccio/verdaccio/issues/1334 I wouldn't no change that. I'll add it to the check list, but better don't do it in this PR. Logger will change soon or later, I agree there are pitfalls like that one you described.

**Comment by mlucool** [comment]
So what should we do to move this forward?

**Comment by juanpicado** [comment]
I was waiting your comments, but we need to remove `logger.warn('Verdaccio started');`, since it pops up twice and does not look good in the terminal.

**Comment by mlucool** [comment]
The above comment has been fixed

**Comment by juanpicado** [comment]
hi @mlucool I could not test it yet, completely forgot it.  perhaps cc: @verdaccio/collaborators can help checking this to ship it asap, or maybe me a long the week.

**Pull request merged**
