### PR TITLE
Added documentation to the PROTOCOL configuration

### PR DESCRIPTION
**Pull request by markpeterfejes**
**Type:** feature

The following has been addressed in the PR: Missing documentation for PROTOCOL config

Added the documentation that was missing for my last pull request.

### CODE REVIEW

**Comment by juanpicado** [comment]
😄  thanks ! cool !

**Comment by markpeterfejes** [comment]
What do you think about an example kubernetes deployment json? It would maybe help some people. It took me a little while to figure it out myself how would it be good

**Comment by markpeterfejes** [comment]
Like this: https://gist.github.com/markpeterfejes/e3897eecb5d4541fc344d71225fa378d

**Comment by juanpicado** [comment]
Feel free to extend this one https://github.com/verdaccio/docker-examples/tree/master/kubernettes-example ⚠️  the huge typo ⚠️ I made 😄 . Also increase the doc is also good idea.

**Comment by markpeterfejes** [comment]
Ohh! Looks good! Will do! It definitely needs a link to it in this repo!

**Pull request merged**
