### PR TITLE
feat: UI search uses search endpoint for global search

### PR DESCRIPTION
**Pull request by juanpicado**
**Only V6 alpha**

Search based on remote, local and private cache. It removes the `Search` Index that was only able to save in memory those packages were private. This feature allows the plugin to search more efficiently, it merge the local results with the one collected from all uplinks, sort and remove duplicates. The UI search directly on the same logic that `npm search´uses. It display label to visualize where is the origin of the package, wheter is private, cache or remote. Displays the latest published version and a short description in the autosuggest. 

The local storage plugin search is based on glob all fodlers, so does not read the package.json anymore which make much efficient since is stateless and non-blocking.

### 💥 Breaking changes
- If you were relying on the web search endpoint the output is completely different
- If you have your own User Interface this will break your functionality

> The UI is prettu basic, could be improved feel free to provide feedback.

image

### CODE REVIEW

**Comment by lirantal** [comment]
That's a pretty cool feature. Maybe we should be marking the results with a label somewhere that shows if it's a local private package or one from a remote registry? Also keep in mind dependency confusion here.

**Comment by juanpicado** [comment]
> That's a pretty cool feature. Maybe we should be marking the results with a label somewhere that shows if it's a local private package or one from a remote registry? Also keep in mind dependency confusion here.

Not the best design but this is the idea

image

The field private would be defined by the plugin itself. I've added Remote but the idea would be find the way to identify from which remote is comming from, since remote are defined as uplinks we know whould be the remote used.

Does looks better?

**Comment by lirantal** [comment]
Oh yes, that's really cool.

**Comment by juanpicado** [comment]
Ok, the status is like this:

- Search in all uplinks, on this demo I do have Nexus3 and npmjs as proxies
- Add label based on the origin, cached if is cache, remote if comes from the proxies and does not exist locally, private if is a private package.
- It uses the same `npm search` endpont with some internal magic sauce to remove duplicates, apply scoring (by default 1 on private packages)
- It's fairly fast, allows search any package, so if you click on any remote one, will became cached.
- What's pending, error handling, probably I'll log errors on the terminal for proxies failires, but the enpoint only would fail if the backend is nor reachable, but if remote fails I won't include results and display cached and private
- About remotes, at this point (due the design) I cannot figure out from which proxie the package is being search, maybe in the future can be improved.

More feedback is welcome.

https://user-images.githubusercontent.com/558752/159170421-9ce991b6-ca76-45c4-bfc7-de21c497d3c0.mp4

**Comment by sumanbh** [comment]
Thoughts on prioritizing private packages on the list over remote ones? So that private packages show up on top.

**Comment by juanpicado** [comment]
> Thoughts on prioritizing private packages on the list over remote ones? So that private packages show up on top.

That make sense, thanks @sumanbh

**Pull request merged**
