### PR TITLE
WIP: logger replacement

### PR DESCRIPTION
**Pull request by jsumners**
**Type:** feature

The following has been addressed in the PR:

*  There is a related issue: #388 #376
*  Unit or Functional tests are included in the PR

**Description:**

**DO NOT MERGE YET**. This is a work in progress PR to replace the internal logger. The replacement's goal is to:

+ reduce the amount of custom code needed around logging
+ standardize the logging API, e.g. by using widely accepted format strings
+ promote external log management for rotation and storage

Currently, I am stalled waiting on an upstream issue to be resolved https://github.com/pinojs/express-pino-logger/issues/14 . It should be resolved in the next few days, and I will be able to resume this PR.

I am submitting this work in progress to show what I am doing and to solicit feedback. Once the PR is complete, I will publish much more detail (i.e. examples) here.

### CODE REVIEW

**Comment by juanpicado** [comment]
Thanks, I'll hold this until you finish.

**Comment by juanpicado** [comment]
You will need to rebase your branch.

**Comment by juanpicado** [comment]
It would be great if you find a way to ....
```
warn --- config file  - /Users/xxxx/.config/verdaccio/config.yaml
warn --- http address - http://localhost:4873/ - verdaccio/2.6.6
```
Avoid display `warn` using warn when start verdaccio. I always thought is kinda misleading

**Comment by jsumners** [comment]
Would you rather they be `info` or `debug`?

**Comment by juanpicado** [comment]
Perhaps such messages should be part of the `logger` at all.

**Comment by juanpicado** [comment]
Just FYI.  You must follow this commit guideline https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#git-commit-guidelines in future commits. Changelog is created automatically and also CI does the release based on that :)

**Comment by jsumners** [comment]
I don't understand what the problem is.

**Comment by juanpicado** [comment]
Ok, we have 2 issues here.

1. Commit messages.  (I'll refer to https://github.com/verdaccio/verdaccio/pull/424#issuecomment-349399158 ) for brevity.
So, your commit instead `Initial logger refactor commit` should be `refactor: Initial logger refactor commit` 
https://github.com/verdaccio/verdaccio/pull/408/commits/0c6f49dc74bee34ae73d0e699e989afdb01d4f02
When you finish, your last commit should be something like.
`feat: new logging system based on pinojs`
Then our changelog generator will reflect your feature.

2. Rebase. Your branch is completely outdated. You must rebase on top of `3.x` and resolve all conflicts (sorry about that, the guys were doing a lot of changes last weekend). You have to keep your branch updated otherwise merge is impossible. The `3.x` is a highly active repo these days.

**Comment by jsumners** [comment]
I have been giving this some thought over the last few days. Unfortunately, I have come to the conclusion that it is too difficult to contribute to this project and will be closing this PR. Thank you for your time. I look forward to the 3.x release.

**Pull request closed without merging**
