### PR TITLE
refactor: use mkdirSync with the recursive option instead of mkdirp

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**
refactor

The following has been addressed in the PR:

*  This PR replaces `mkdirp` with `fs.mkdirSync` using the `recursive` option.

See https://repl.it/repls/OpulentIndelibleRuntimelibrary

**This will break compatibility with Node.js < 10.12**

https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options

v10.12.0 | The second argument can now be an options object with recursive and mode properties.
-- | --

**Description:**

In the near future we do not need `mkdirp` anymore and can use `fs.mkdirSync` then.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Seems if we update `flow-bin` to `0.90.0` we will get this fixed but get errors due to other components.

<details>
<summary>flow check</summary>

```
$ flow check
Error --------------------------------------------------------------------------- flow-typed/npm/marked_v0.3.x.js:154:16

Cannot use function type as a type because function type is a value. To get the type of a value use `typeof`.

   154|   inlinelexer: marked$InlineLexer.output;
                       ^^^^^^^^^^^^^^^^^^^^^^^^^


Error ---------------------------------------------------------------------------------- src/api/endpoint/index.js:34:20

Cannot call `app.param` with `validateName` bound to `callback` because function [1] requires another argument from
function type [2].

   src/api/endpoint/index.js:34:20
    34|   app.param('tag', validateName);
                           ^^^^^^^^^^^^

References:
   src/api/middleware.js:39:8
    39| export function validateName(req: $RequestExtend, res: $ResponseExtend, next: $NextFunctionVer, value: string, name: string) {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   flow-typed/npm/express_v4.16.x.js:191:15
                      v-
   191|     callback: (
   192|       req: $Subtype<express$Request>,
   193|       res: express$Response,
   194|       next: express$NextFunction,
   195|       id: string
   196|     ) => mixed
            ---------^ [2]


Error ---------------------------------------------------------------------------------- src/api/endpoint/index.js:35:24

Cannot call `app.param` with `validateName` bound to `callback` because function [1] requires another argument from
function type [2].

   src/api/endpoint/index.js:35:24
    35|   app.param('version', validateName);
                               ^^^^^^^^^^^^

References:
   src/api/middleware.js:39:8
    39| export function validateName(req: $RequestExtend, res: $ResponseExtend, next: $NextFunctionVer, value: string, name: string) {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   flow-typed/npm/express_v4.16.x.js:191:15
                      v-
   191|     callback: (
   192|       req: $Subtype<express$Request>,
   193|       res: express$Response,
   194|       next: express$NextFunction,
   195|       id: string
   196|     ) => mixed
            ---------^ [2]


Error ---------------------------------------------------------------------------------- src/api/endpoint/index.js:36:25

Cannot call `app.param` with `validateName` bound to `callback` because function [1] requires another argument from
function type [2].

   src/api/endpoint/index.js:36:25
    36|   app.param('revision', validateName);
                                ^^^^^^^^^^^^

References:
   src/api/middleware.js:39:8
    39| export function validateName(req: $RequestExtend, res: $ResponseExtend, next: $NextFunctionVer, value: string, name: string) {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   flow-typed/npm/express_v4.16.x.js:191:15
                      v-
   191|     callback: (
   192|       req: $Subtype<express$Request>,
   193|       res: express$Response,
   194|       next: express$NextFunction,
   195|       id: string
   196|     ) => mixed
            ---------^ [2]


Error ---------------------------------------------------------------------------------- src/api/endpoint/index.js:37:22

Cannot call `app.param` with `validateName` bound to `callback` because function [1] requires another argument from
function type [2].

   src/api/endpoint/index.js:37:22
    37|   app.param('token', validateName);
                             ^^^^^^^^^^^^

References:
   src/api/middleware.js:39:8
    39| export function validateName(req: $RequestExtend, res: $ResponseExtend, next: $NextFunctionVer, value: string, name: string) {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   flow-typed/npm/express_v4.16.x.js:191:15
                      v-
   191|     callback: (
   192|       req: $Subtype<express$Request>,
   193|       res: express$Response,
   194|       next: express$NextFunction,
   195|       id: string
   196|     ) => mixed
            ---------^ [2]


Error ----------------------------------------------------------------------------------------- src/api/web/api.js:31:26

Cannot call `route.param` with `validateName` bound to `callback` because function [1] requires another argument from
function type [2].

   src/api/web/api.js:31:26
    31|   route.param('version', validateName);
                                 ^^^^^^^^^^^^

References:
   src/api/middleware.js:39:8
    39| export function validateName(req: $RequestExtend, res: $ResponseExtend, next: $NextFunctionVer, value: string, name: string) {
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]
   flow-typed/npm/express_v4.16.x.js:191:15
                      v-
   191|     callback: (
   192|       req: $Subtype<express$Request>,
   193|       res: express$Response,
   194|       next: express$NextFunction,
   195|       id: string
   196|     ) => mixed
            ---------^ [2]


Error -------------------------------------------------------------------------------------------- src/lib/auth.js:52:12

Missing type annotation for `T`. `T` is a type parameter declared in function [1] and was implicitly instantiated at
call of `loadPlugin` [2].

   src/lib/auth.js:52:12
                  v-------------------------------------------------------------------------
   52|     return loadPlugin(config, config.auth, pluginOptions, (plugin: IPluginAuth) => {
   53|       const { authenticate, allow_access, allow_publish } = plugin;
   54|
   55|       return authenticate || allow_access || allow_publish;
   56|     });
           -^ [2]

References:
   src/lib/plugin-loader.js:52:16
   52| export default function loadPlugin<T>(config: Config, pluginConfigs: any = {}, params: any, sanityCheck: Function, prefix: string = 'verdaccio'): T[] {
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1
]


Error ------------------------------------------------------------------------------------ src/lib/config-utils.js:45:10

Missing type annotation for `T`. `T` is a type parameter declared in function type [1] and was implicitly instantiated
at call of method `flatten` [2].

   src/lib/config-utils.js:45:10
    45|   return _.flatten(result);
                 ^^^^^^^^^^^^^^^^^ [2]

References:
   flow-typed/npm/lodash_v4.x.x.js:257:5
   257|     flatten<T, X>(array?: ?Array<Array<T> | X>): Array<T | X>;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]


Error ------------------------------------------------------------------------------------ src/lib/config-utils.js:45:10

Missing type annotation for `X`. `X` is a type parameter declared in function type [1] and was implicitly instantiated
at call of method `flatten` [2].

   src/lib/config-utils.js:45:10
    45|   return _.flatten(result);
                 ^^^^^^^^^^^^^^^^^ [2]

References:
   flow-typed/npm/lodash_v4.x.x.js:257:5
   257|     flatten<T, X>(array?: ?Array<Array<T> | X>): Array<T | X>;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [1]


Error ---------------------------------------------------------------------------------------- src/lib/storage.js:317:41

Cannot call `self.uplinks[up_name].search` because property `search` is missing in `IProxy` [1].

   src/lib/storage.js:317:41
   317|         const lstream: IUploadTarball = self.uplinks[up_name].search(options);
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

References:
   types/index.js:53:18
    53|   [key: string]: IProxy;
                         ^^^^^^ [1]


Error ------------------------------------------------------------------------------------- src/lib/up-storage.js:554:26

boolean [1] is incompatible with string [2].

   src/lib/up-storage.js:554:26
   554|       if (this.proxy === false) {
                                 ^^^^^ [1]

References:
   src/lib/up-storage.js:53:10
    53|   proxy: string;
                 ^^^^^^ [2]


Error ----------------------------------------------------------------------------------------- test/lib/server.js:75:28

Missing type annotation for `data`.

   75|   putPackage(name: string, data) {
                                  ^^^^



Found 12 errors
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

**Comment by juanpicado** [comment]
Let’s adrede Flow upgrade in a different PR, I was holding it but I think we should do it

**Comment by DanielRuf** [comment]
> This will break compatibility with Node.js < 10.12

We should do this in a major release imho.

**Comment by juanpicado** [comment]
:) that is 365 days ...

**Comment by DanielRuf** [comment]
> in any case this is a feat

Not sure but currently it is a refactor (refactor the package out and use the native methods). Not a new feature per se ;-)

**Comment by DanielRuf** [comment]
> :) that is 365 days ...

Should be fine as 10 LTS will end on 2020-04-01, see https://nodejs.org/en/about/releases/

But I'm open for discussions if we should do this change earlier which is a big breaking change (no more Node.js 8 and 10 support).

**Comment by juanpicado** [comment]
We can do this in the branch 5.x

**Comment by DanielRuf** [comment]
I think I have to rebase then?

**Comment by juanpicado** [comment]
You might ... but I think might be easier from scratch the 5.x is quite different structure

**Comment by juanpicado** [comment]
Closing this, `master` is completely different  now.

**Pull request closed without merging**
