### PR TITLE
fix: remove useless secureProtocol option

### PR DESCRIPTION
**Pull request by jinliming2**
Why we specified `secureProtocol: 'SSLv23_method'` here?
The comment after the code said `"disable insecure SSLv2 and SSLv3"`, but that was what the code next line do: `secureOptions: constants.SSL_OP_NO_SSLv2 | constants.SSL_OP_NO_SSLv3,`.

The default value of `secureProtocol` is [`SSLv23_method` in Node.JS 8 LTS](https://nodejs.org/docs/latest-v8.x/api/tls.html#tls_tls_createsecurecontext_options), but [none and use minVersion in Node.JS 10 LTS](https://nodejs.org/docs/latest-v10.x/api/tls.html#tls_tls_createsecurecontext_options).

`SSLv23_method` was in the OpenSSL manual version 1.0.2, but removed in the version 1.1.0. So it may not works in Node.JS 10.

I think we should remove this line to use the default value of Node.JS.

### CODE REVIEW

**Comment by juanpicado** [comment]
> Why we specified secureProtocol: 'SSLv23_method' here?
Legacy from `sinopia`, that knowledge is lost unfortunately. 

> I think we should remove this line to use the default value of Node.JS.

I'm kinda agree with you, but let me read a bit about it. In any case. I'd love you update the commit message with `fix:` otherwise I cannot release as a patch.

**Comment by jinliming2** [comment]
Commit message was updated.

**Comment by juanpicado** [comment]
@jinliming2 I think I found some context about the comment https://gist.github.com/mildmojo/1ec26482ee6bd777a608#file-tls_creds-js-L25

**Comment by juanpicado** [comment]
Nevermind :-) totally old anduseless property. 
https://github.com/nodejs/node-convergence-archive/issues/51#issuecomment-109499815

**Comment by juanpicado** [comment]
Thanks @jinliming2 for your contribution, it was already published.

**Pull request merged**
