### PR TITLE
fix: doubled request logs in node.js >= 11

### PR DESCRIPTION
**Pull request by frimuchkov**
```
$ docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio warn --- config file  - /verdaccio/conf/config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/4.9.1
 http --> 200, req: 'GET https://registry.npmjs.org/execa' (streaming)
 http --> 200, req: 'GET https://registry.npmjs.org/execa', bytes: 0/119164
 http <-- 200, user: null(172.17.0.1), req: 'GET /execa', bytes: 0/27224
 http <-- 200, user: null(172.17.0.1), req: 'GET /execa', bytes: 0/27224
```

### CODE REVIEW

**Comment by frimuchkov** [comment]
As far, as I see, "E2E Jest with verdaccio" fails in every PR

**Comment by juanpicado** [comment]
I see you are using a custom config file `$ docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio warn --- config file  - /verdaccio/conf/config.yaml`

can you share what do you have there?

**Review by juanpicado — CHANGES_REQUESTED** [review]
Thanks for noticing this, I did deeply checkout the `middleware.ts` and I think the mistake is on this line

```
 req.on('close', function(): void {
    log();
 });
```

Actually we do not need it at all. Since the `final` middleware already triggers `res.send(body);` which at the same time ends the request and we call `log();` in the line 269.

**Comment by juanpicado** [comment]
btw, could you adapt according the guidelines ? 

https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#commit-guidelines

**Comment by frimuchkov** [comment]
> Actually we do not need it at all. Since the `final` middleware already triggers `res.send(body);` which at the same time ends the request and we call `log();` in the line 269.

Not exactly, "the `end` event will not be emitted unless the data is completely consumed" (https://nodejs.org/dist/latest/docs/api/stream.html#stream_event_end), so, if something go wrong, we stream will emit only `close`

**Comment by frimuchkov** [comment]
> btw, could you adapt according the guidelines ?
> 
> https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#commit-guidelines

I'v done

**Review by juanpicado — APPROVED** [review]
LGTM 

Thanks !  :upside_down_face:

**Pull request merged**
