### PR TITLE
fix: correctly check if the proxy setting evaluates to false

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**
bug

The following has been addressed in the PR:

*  The `property` check was checking for a boolean but the typings expect a string.

**Description:**
See https://github.com/verdaccio/verdaccio/blob/5a8d92f5f93c16f505f51dddecd1c2d520771971/src/lib/up-storage.js#L53

### CODE REVIEW

**Comment by DanielRuf** [comment]
> Ok, if both methods pass the test then we have something wrong there, I will check it when I am back.

I saw the failing flow checks when I was upgrading `flow-bin`. Seems previous versions do not correctly check this.

**Comment by juanpicado** [comment]
Yes, Flow always fails in upgrade due new features they add. Make sense to me upgrade.

**Comment by DanielRuf** [comment]
> Ok, if both methods pass the test then we have something wrong there, I will check it when I am back.

Not sure what you mean but `""` and `false` both evaluate to false when using `!`.

https://repl.it/repls/AccomplishedObviousDatamart

**Comment by juanpicado** [comment]
Thanks @DanielRuf

**Pull request merged**
