### PR TITLE
refactor: remove all assert imports

### PR DESCRIPTION
**Pull request by Utwo**
**Type:**

The following has been addressed in the PR:

*  There is a related issue?
*  Unit or Functional tests are included in the PR

**Description:**

### CODE REVIEW

**Comment by Utwo** [comment]
Hmmm.. strange, tests works locally

**Comment by juanpicado** [comment]
```
Setup Verdaccio Servers
Running registry /config-1.yaml on port 55551
/home/circleci/verdaccio/test/lib/server.js:36
    expect(options.uri).toBeDefined();
```

**Comment by Utwo** [comment]
Thank you guys!

**Comment by juanpicado** [comment]
Thank you for your contributions!! 🏅

**Pull request merged**
