### PR TITLE
feat: Expose entire server in a subpath

### PR DESCRIPTION
**Pull request by marcoreni**
**Type:** feature

The following has been addressed in the PR:
*  Unit tests are included in the PR

**Description:**
There are scenarios where it's not possible to use a reverse-proxy, but the server cannot be exposed inside the root (eg. AWS Cloudfront as a proxy). 
This feature adds a configuration value that allows to expose the entire webserver inside a subpath.

It maintains compatibility with url_prefix configuration.

*NOTE:* a change in `@verdaccio/types` is also requested. Right now I've worked-around with `// $FlowFixMe `

### CODE REVIEW

**Comment by juanpicado** [comment]
hi @marcoreni , thanks for the PR. I'd need you elaborate some scenarios where this is useful. The documentation you added is a bit light and I still do not get it.

**Comment by marcoreni** [comment]
Hello @juanpicado , I'll describe our scenario, hope that this will help clarify our need.

We are using a single AWS Cloudfront CDN as a single entrypoint for different backend applications. We expose each application in a subpath (for example, Verdaccio would be exposed to http://example.cloudfront.net/verdaccio ). 

Cloudfront has limited proxy capabilities, therefore if you declare a behavior with a specific path pattern ( /verdaccio) this will be forwarded to the backend as-is, with no possibilities of pointing to a root path.

We can resolve this in two ways:
1- add a second proxy (Nginx) in order to apply a reverse-proxy configuration
2- expose Verdaccio in a subpath. 

Solution 1 would have additional costs compared to solution 2, therefore we implemented this.

Let me know if this can be useful for others.

PS: while executing the tests on my machine they were all successful. I'm having flapping results on circle-ci, but they don't seem related to my edits.

**Comment by juanpicado** [comment]
I was testing ... I needed a clean storage, no lock file (due resolve field) but ...
This approach forces any middleware to go through the base url which breaks the audit plugin. 😞 

```
 warn --- http address - http://localhost:4873/ - verdaccio/3.6.0
 info <-- 127.0.0.1 requested 'POST /verdaccioprefix/-/npm/v1/security/audits'
 http <-- 404, user: undefined(127.0.0.1), req: 'POST /verdaccioprefix/-/npm/v1/security/audits', bytes: 20856/180
```
and should be

```
 warn --- http address - http://localhost:4873/ - verdaccio/3.7.0
 info <-- 127.0.0.1 requested 'POST /-/npm/v1/security/audits'
 http <-- 200, user: null(127.0.0.1), req: 'POST /-/npm/v1/security/audits', bytes: 20856/217
```
We share the  express `app` with middleware plugins.

**Comment by marcoreni** [comment]
I totally missed the middlewares, sorry! 

Middlewares were not routed through the base_path and I think this caused the issue. 
I have no experience with `npm audit`, but I think that that endpoint (and other endpoints exposed by different plugins) should be exposed inside the subpath as well. 

I pushed a fix after testing `npm audit` :
```
 info <-- 172.17.0.1 requested 'POST /npmrepo/-/npm/v1/security/audits'
 http <-- 200, user: undefined(172.17.0.1), req: 'POST /npmrepo/-/npm/v1/security/audits', bytes: 841/210
 http <-- 200, user: undefined(172.17.0.1), req: 'POST /npmrepo/-/npm/v1/security/audits', bytes: 841/210
 http <-- 200, user: undefined(172.17.0.1), req: 'POST /npmrepo/-/npm/v1/security/audits', bytes: 841/210
 http <-- 200, user: undefined(172.17.0.1), req: 'POST /npmrepo/-/npm/v1/security/audits', bytes: 841/210
```
```
$ npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 9 scanned packages
```

Does it seem right to you?

**Comment by juanpicado** [comment]
Thanks I will review it again along the weekend :-)

**Pull request closed without merging**
