### PR TITLE
chore: build add node13

### PR DESCRIPTION
**Pull request by juanpicado**
**Description:**

Before check others PR I want to clarify how we are testing, I add Node 13 to be more explicit since the LTS are having a long maintenance https://nodejs.org/en/about/releases/ most likely we will have 4 versions running for a while.

Furthermore reorganize the steps, E2E goes to the end and then coverage. Also updates GitHub CI to use node 13.

Screen Shot 2019-12-13 at 7 47 52 AM

E2E will be soon not more UI anymore, rather our own package being tested as we advise to (short future term).

### CODE REVIEW

**Comment by DanielRuf** [comment]
We should probably `latest` to fail early. Otherwise we have to update this every time.

**Comment by DanielRuf** [comment]
We should probably use `latest` to fail early. Otherwise we have to update this every time.

**Comment by juanpicado** [comment]
> We should probably use `latest` to fail early. Otherwise we have to update this every time.

I'm not 100% sure what you meant, but here my thoughts.  Before we were explicit, yes we had to upgrade this file but not periodically, for a while has been less explicit but on every visit is hard to know what is being tested against. So I want to back to be explicit again to avoid be forget  add new versions.

**Comment by DanielRuf** [comment]
I meant the `latest` or `node` tag instead of `13` so CI will automatically use `14` when it is released.

**Pull request merged**
