### PR TITLE
Update the configs to fully support proxying scoped packages

### LINKED ISSUE #55: Unable to install scoped packages, e.g. @angular/common
`npm install @angular/common`

gives

```
npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/home/UX/fziacikux/.nvm/versions/node/v6.3.1/bin/node" "/home/UX/fziacikux/.nvm/versions/node/v6.3.1/bin/npm" "install" "@angular/common"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 no such package available : @angular/common
npm ERR! 404 
npm ERR! 404  '@angular/common' is not in the npm registry.

```

Log file attached.
[npm-debug.zip](https://github.com/verdaccio/verdaccio/files/444595/npm-debug.zip)

### PR DESCRIPTION
**Pull request by ChadKillingsworth**
Fixes #55

### CODE REVIEW

**Comment by nwhite89** [comment]
I've tried this out but it doesn't work for me I'm afraid with `@angular/common` for example

**Comment by kachkaev** [comment]
@nwhite89 what exactly is not working for you?

**Comment by nwhite89** [comment]
using my config to the same as the PR if i try and install `@angular/common` it will be unable to find it (won't proxy through to the original npm from my own).

**Comment by nwhite89** [comment]
@kachkaev apologies I followed to this PR from sinopia discussion it works with the latest version of this however, unfortunately I can't use Verdaccio as all of my packages need to be authorised and this package currently fails with authorised users.

**Comment by trentearl** [comment]
Great thanks for looking into this!
Fixed in: 6f7a28b3594fdd3412928b5c597ab5fff1011461

**Pull request closed without merging**
