### PR TITLE
feat: new environment variable (storage path) 

### PR DESCRIPTION
**Pull request by osher**
Follow up of https://github.com/verdaccio/verdaccio/pull/2199 in v5

### CODE REVIEW

**Comment by juanpicado** [comment]
Run `yarn format`, everything else is pretty much ok.

**Comment by osher** [comment]
I'm working online using github web-ui, I did not even check out the repo...
I hoped the CI will tell me what's wrong so I can fix it - perhaps you can help me?

**Comment by juanpicado** [comment]
> I'm working online using github web-ui, I did not even check out the repo... I hoped the CI will tell me what's wrong so I can fix it - perhaps you can help me?

Done, it was hard to see on this UI

**Review by juanpicado — APPROVED** [review]
Thanks @osher you 🎸

**Comment by osher** [comment]
nonono - thank you.

So, the merger to `5.x ` should result with a bumped version and a `verdaccio/verdaccio:5.5.3` docker, or there's one more step?

P.S
you're fun to work with. that gave me appetite.
maybe I'll check out that repo one day and overcome my TS fude ...but not today 😛 🤷

**Comment by juanpicado** [comment]
I need to check what's happening here https://github.com/verdaccio/verdaccio/pull/2984 and release only takes 1 min on my side.

**Comment by osher** [comment]
It's ok, I saw the situation, we'll wait patiently.

Meanwhile - we found [`verdaccio:5.x-next` ](https://github.com/verdaccio/verdaccio/runs/5190096823?check_suite_focus=true) that was published automatically, so no urgency

keep up the good work!

**Comment by juanpicado** [comment]
Released https://github.com/verdaccio/verdaccio/releases/tag/v5.6.0

**Comment by juanpicado** [comment]
ok, message received :) let me some days to digest, these days I'm busy here https://nodecongress.com/ as speaker 😊

**Comment by osher** [comment]
well!! good luck!

can you just say if you have something up the sleve for an env for the log path?

**Comment by juanpicado** [comment]
> If I'm smart enough to design the config-tree without any arrays (which you have!)

In v6 we don't have arrays anymore, I've removed them because does not make sense nowadays. Anyway your idea seems something I've heard https://github.com/verdaccio/verdaccio/issues/1681 before, I also into the idea that env variables helps a lot in eg: Docker etc

I had others ideas that might conflict with this one, like use a object schema to validate the config file (like yarn +v2 is doing with `.yarnc.yaml` file but nothing definitive yet, at leas for next major.

Let me digest more this when my brain get more relaxed. Feel free to remind me over time, I usually get distractec with so many open topics, or maybe better open a discussion so I can tag it correctly.

**Comment by edclement** [comment]
Just my 2 cents... everything being discussed here related to configuration seems like a perfect use case for using the [config](https://www.npmjs.com/package/config) package. You can specify config by file, environmental variable, command line, or all of the above and it handles the merging.

**Comment by osher** [comment]
@edclement  Thanks for the comment 😄 

I did mention the `config` pacakge above.
however, AFAIK it's doing only half of the story as it does not handle CLI-arguments. It's also much more then necessary with it's local-cascading model of the hostname, instance name, env (what they call deployment).

So whenever I use it I combine it with `minimist` which is the actual parser behind `yargs` (like `config`, yargs is doing much more with custom-commands and message formatting).

But that's just me and my fanatic approach towards slim deliveries... both `yargs` and `config` are great packages I was pushing for a long while.

**Pull request merged**
