### PR TITLE
Indiescripter/align website format lint configs

### PR DESCRIPTION
**Pull request by indiescripter**
Started out with idea of just fixing the eslint breakage in website master but instead went this way:

1) Updated heaps more package deps

2) Then found problem with eslint config in website caused by airbnb-typescript config so switched to @verdaccio/eslint tools package

3) Changed to using top-level `.prettierrc` by deleting the one in website. This brought website formatting printWidth to 100 columns as discussed time ago and is now same as packages/*

Have left all individual commits & associated messages in place so easier to see what happened step-by-step; suggest squashing into a single commit before adding into master.

```
    style: eslint-config-airbnb-typescript => @verdaccio/eslint-config; use prettier width 100 in website
    build: remove some legacy flow-typed cruft
    build: update web devDep node-html-parser
    build: update logger dep pino minor version
    build: update ui-theme devDep github-markdown-css
    build: update website devDev sass
    build: update e2e-cli deps npm & pnpm
    build: update dev/devDeps node-fetch, react-hook-form
    build: update devDep eslint-plugin-prettier
    build: update devDep terser-webpack-plugin
    build: update devDeps @typescript-eslint/*; deps aws-sdk & memfs
    build: update dep http-status-codes
    build: remove unused devDep wait-on
    build: update deps dompurify, esbuild-loader, envinfo, express-rate-limit, fastify, handlebars, jsdom
    build(deps): [security] bump https-proxy-agent from 2.2.2 to 2.2.4 (#1582)
```

AFAIK Only problem remaining is when running

`pnpm eslint:check --recursive`

there's a react hook problem which hope @juanpicado can fix please.

```
Scope: all 42 workspace projects
website eslint:check$ eslint src/**/*.tsx
│ Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
│ /home/mars/current-universe/verdaccio-dev/website/src/components/Features.tsx
│   48:41  error  React Hook "useBaseUrl" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
│ ✖ 1 problem (1 error, 0 warnings)
└─ Failed in 2.2s
/home/mars/current-universe/verdaccio-dev/website:
 ERROR  @verdaccio/website@5.1.3 eslint:check: `eslint src/**/*.tsx`
Exit status 1
```

### CODE REVIEW

**Comment by semoal** [comment]
Hi Justin, really appreciated these changes.
About the eslint error, you just need to change line 48 of Features.tsx to this:
```tsx
{FEATURES.map(({ image, title, subtitle }) => {
          const imageUrl = useBaseUrl(image)
          return (
            <FeatureCard key={title} image={imageUrl} title={title} subtitle={subtitle} />
          )
        })}
```

This should work fine with eslint.

**Comment by indiescripter** [comment]
Thanks @semoal. Will give it a shot :)

**Comment by indiescripter** [comment]
Hmm, still a problem @semoal

```
const Features = (): React.ReactElement => (
  <section className={styles.features}>
    <div className={styles['features--wrap']}>
      {FEATURES.map(({ image, title, subtitle }) => {
        const imageUrl = useBaseUrl(image);
        return <FeatureCard key={title} image={imageUrl} title={title} subtitle={subtitle} />;
      })}
    </div>
    <div className={styles.linkFeatures}>
      <Link to={useBaseUrl('/docs/configuration')} className="link-primary">
        <Translate>Discover more features</Translate>
      </Link>
    </div>
  </section>
);
```

```
 /home/mars/current-universe/verdaccio-dev/website/src/components/Features.tsx
│   48:26  error  React Hook "useBaseUrl" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
│ ✖ 1 problem (1 error, 0 warnings)
```

**Comment by semoal** [comment]
Fixed :) LGTM, Juan it's really busy this week but I'm sure he'll merge this asap

**Review by semoal — APPROVED** [review]

**Comment by juanpicado** [comment]
thank you guys :) !! 😄

**Comment by indiescripter** [comment]
Thanks @semoal for picking up right at the end. I'm sure @juanpicado really appreciated that & of course so do I :)

**Comment by indiescripter** [comment]
Just a quick heads up to be on the lookout for a `node-fetch@3.x.x` update to fix this [known export issue with `v3.0.0`](https://github.com/node-fetch/node-fetch/issues/1266) reported just a few days ago.

We are using `node-fetch@3.0.0-beta.6-exportfix` for the moment which works but somehow got messed up in latest `v3.0.0`.

**Pull request merged**
