### PR TITLE
fix: publish with deprecated field

### PR DESCRIPTION
**Pull request by Jiasm**
When publish with deprecated field in `package.json`, that will make all old versions miss.

Examples:

I have package@1.0.0 and package@1.0.1.

When `npm deprecate package@1.0.0 "xxx"`, Verdaccio will recived:

```json
{
  "name": "module_name",
  "version": {
    "1.0.0": {
      "deprecated": "xxx"
    },
    "1.0.1": {}
  }
}
```

⬆️ This make sense

But then publish new version with @1.0.2.

Verdaccio will recived:

```json
{
  "name": "module_name",
  "version": {
    "1.0.2": {
      "deprecated": "xxx" // if we set this field in package.json
    },
  }
}
```

and that metadata will override package.json, make old version miss.

### CODE REVIEW

**Comment by juanpicado** [comment]
Good catch, j
I haven't reviewed yet but o wonder in which version are you willing to fix it, because master is future major and I guess you might expect on v5, doesn't it ?

**Comment by Jiasm** [comment]
> Good catch  @Jiasm
> 
> I haven't reviewed it yet (maybe you want to wait I can confirm your PR fix it) but o wonder in which version are you willing to fix it, because the master is a future major and I guess you might expect it on v5, doesn't it?
> 
> 
> 
> Just FYI, I'm currently refactoring the publish method so maybe you want to fix it on the branch `5.x` (which is current stable version) and I could take care of the master branch on my current work in progress..

Hi @juanpicado , I want fix it on 5.x,and I will try regroup my code for running CI in tomorrow😁

**Comment by juanpicado** [comment]
Sure, don't forget read carefully the contribution guidelines, if you have questions do not hesitate to ping me.

**Comment by Jiasm** [comment]
move to #2771

**Pull request closed without merging**
