### PR TITLE
docs: update e2e pages

### PR DESCRIPTION
**Pull request by gweesin**
fix typos, update star counts and so on.

### CODE REVIEW

**Comment by mbtools** [comment]
How about replacing these with badges so we don't have to update the page again:

`Stars`

Stars

**Comment by gweesin** [comment]
> How about replacing these with badges so we don't have to update the page again:
> 
> `Stars`
> 
> Stars

Good idea!

**Review by mbtools — APPROVED** [review]
Thanks 👍

**Comment by juanpicado** [comment]
@gweesin I just noticed Bun also uses verdaccio and is not at the list
https://github.com/oven-sh/bun/commits/main/test/cli/install/registry/verdaccio.yaml in case you want to PR

**Comment by gweesin** [comment]
Yes, I will make the commit in a few hours.

**Pull request merged**
