### PR TITLE
fix: prevent issue with leading hyphen in package name - fixes #1429

### LINKED ISSUE #1429: Package with dash in its name fails to install with Yarn and NPM
**Describe the bug**

This package: https://yarnpkg.com/en/package/@ember-data/-build-infra is sub dependency of ember-data package. When trying to install ember-data@3.11 or @ember-data/-build-infra package directly served by Verdaccio, Verdaccio will return 404 error.

**To Reproduce**

Make sure package is not already on local cache.

`yarn add @ember-data/-build-infra` or `npm install @ember-data/-build-infra`

**Expected behavior**

Package to be successfully installed.

**Environment information**

Verdaccio 4.2.0
Yarn v1.17.3
NPM v6.4.1

**Screenshots**

Seems like there is no tarball stored on disk at all.

Screenshot 2019-08-05 at 17 12 37

### PR DESCRIPTION
**Pull request by DanielRuf**
**Type:**
bugfix

The following has been addressed in the PR:

*  Prevent issue with leading hyphen / dash in package names

**Description:**
It seems the handling and passing of routes and paths changed. Depending on where we are (-/ping or -/web/detail/kleur) we either geht `-` or `kleur`. If the package contains a leading hyphen / dash this did not work as it was handled as internal couchdb route (using the `charAt(0)` check).

Resolves #1429

### CODE REVIEW

**Comment by DanielRuf** [comment]
It seems at least one CI check fails here, not sure why. Is this new?

https://github.com/verdaccio/verdaccio/pull/1636/checks?check_run_id=366069732

```
git checkout --progress --force a87309f500b9d51c631788dc8cd37695148cc588
##[error]fatal: reference is not a tree: a87309f500b9d51c631788dc8cd37695148cc588
Removed matchers: 'checkout-git'
##[error]Git checkout failed with exit code: 128
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.163.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```

@juanpicado

**Comment by juanpicado** [comment]
Cool and Interesting, could you give me some examples how that make a different? I'm a bit lost.

**Comment by juanpicado** [comment]
@DanielRuf fixed ...

**Comment by DanielRuf** [comment]
> Cool and Interesting, could you give me some examples how that make a different? I'm a bit lost.

See `/-/ping` and try `yarn add @ember-data/-build-infra` or `npm install @ember-data/-build-infra`.

**Pull request merged**
