### PR TITLE
bug #1105: answer 401 in case no credentials were sent.

### LINKED ISSUE #1105: npm outdated and update does not work, but install works
**Describe the bug**

When I issue an npm outdated or npm update command, npm fails with E403.

**To Reproduce**

1. Log in to private registry (aka have an ~/.npmrc)
2. install a package from your private, password protected repository using `npm install`
3. Try to upgrade your package using `npm update` or invoke `npm outdated`

**Expected behavior**
Should not fail with E403.

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: latest
```
$ docker images verdaccio/verdaccio
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
verdaccio/verdaccio   latest              c542d9e516e4        2 weeks ago         659MB
```

```
$ npm --version
6.4.1
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
storage: /verdaccio/storage
plugins: /verdaccio/plugins

web:
  title: Oblamatik npm repository
  scope: \@oblamatik

auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1

  bitbucket:
    allow: MyTeam

packages:
  '@oblamatik/*':
    access: $authenticated
    publish: $authenticated

middlewares:
  audit:
    enabled: true

logs:
  - {type: stdout, format: pretty, level: http}

max_body_size: 1000mb
```

**Debugging output**

npm update @oblamatik/omw-middleware shows the following output:

```
$ npm update @oblamatik/omw-middleware --verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/mkr/.nvm/versions/node/v8.11.4/bin/node',
npm verb cli   '/home/mkr/.nvm/versions/node/v8.11.4/bin/npm',
npm verb cli   'update',
npm verb cli   '@oblamatik/omw-middleware',
npm verb cli   '--verbose' ]
npm info using npm@6.4.1
npm info using node@v8.11.4
npm verb npm-session 8c99504fa195e079
npm verb update computing outdated modules to update
npm verb request uri https://npm.dev.oblamatik.ch/@oblamatik%2fomw-middleware
npm verb request no auth needed
npm info attempt registry request try #1 at 15:02:09
npm verb request id dc615f7f9a29d1a9
npm http request GET https://npm.dev.oblamatik.ch/@oblamatik%2fomw-middleware
npm http 403 https://npm.dev.oblamatik.ch/@oblamatik%2fomw-middleware
npm verb headers { server: 'nginx/1.14.0',
npm verb headers   date: 'Mon, 05 Nov 2018 14:02:09 GMT',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '96',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-powered-by': 'verdaccio/3.8.1',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   etag: 'W/"60-ddeEwRsYkCfxZ4K8+J1Ht4SxMow"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aV6jFK',
npm verb headers   'strict-transport-security': 'max-age=31536000' }
npm verb stack Error: unregistered users are not allowed to access package @oblamatik/omw-middleware : @oblamatik/omw-middleware
npm verb stack     at makeError (/home/mkr/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:329:12)
npm verb stack     at RegClient.<anonymous> (/home/mkr/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:317:14)
npm verb stack     at Request._callback (/home/mkr/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
npm verb stack     at Request.self.callback (/home/mkr/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/request/request.js:185:22)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at Request.emit (events.js:214:7)
npm verb stack     at Request.<anonymous> (/home/mkr/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/request/request.js:1161:10)
npm verb stack     at emitOne (events.js:116:13)
npm verb stack     at Request.emit (events.js:211:7)
npm verb stack     at IncomingMessage.<anonymous> (/home/mkr/.nvm/versions/node/v8.11.4/lib/node_modules/npm/node_modules/request/request.js:1083:12)
npm verb stack     at Object.onceWrapper (events.js:313:30)
npm verb stack     at emitNone (events.js:111:20)
npm verb stack     at IncomingMessage.emit (events.js:208:7)
npm verb stack     at endReadableNT (_stream_readable.js:1064:12)
npm verb stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:180:9)
npm verb statusCode 403
npm verb pkgid @oblamatik/omw-middleware
npm verb cwd /home/mkr/work/twms/twms-backend
npm verb Linux 4.9.0-7-amd64
npm verb argv "/home/mkr/.nvm/versions/node/v8.11.4/bin/node" "/home/mkr/.nvm/versions/node/v8.11.4/bin/npm" "update" "@oblamatik/omw-middleware" "--verbose"
npm verb node v8.11.4
npm verb npm  v6.4.1
npm ERR! code E403
npm ERR! unregistered users are not allowed to access package @oblamatik/omw-middleware : @oblamatik/omw-middleware
npm verb exit [ 1, true ]
npm timing npm Completed in 1096ms
```

In the verdaccio logs I get the following entries:

```
http <-- 403, user: null(194.230.107.251 via 172.17.0.2), req: 'GET /@oblamatik%2fomw-middleware', error: unregistered users are not allowed to access package @oblamatik/omw-middleware
```

**Analysis**
Not sure, that verdaccio is responsible for this, as user "null" is definitely not allowed. However I am not sure, why npm thinks, that it does not need to send auth (log entry: **npm verb request no auth needed**)

Could you make a statement please?

### PR DESCRIPTION
**Pull request by 0815fox**
I'd like to discuss those minor changes which would resolve #1105 on my opinion:

On my machine the test results are same before and after my changes (not sure if it is my machine or if cases are known to fail in master branch):

```
Test Suites: 4 failed, 42 passed, 46 total
Tests:       41 failed, 3 skipped, 274 passed, 318 total
Snapshots:   30 passed, 30 total
```

Are there test cases affected by this change?

### CODE REVIEW

**Comment by juanpicado** [comment]
@0815fox yes, your changes definitely will affect the unit tests. If you go throw all errors https://circleci.com/gh/verdaccio/verdaccio/11375?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link 

all errors become from

```
Summary of all failing tests
 FAIL  test/unit/api/api.spec.js
```

You need to update the expected messages.

```
expect(res.body.error).toMatch(/unregistered users are not allowed to access package auth-package/);
```

That shold fix all errors.

**Comment by 0815fox** [comment]
So I did not see the issues locally, because 41 tests, including the ones which now really failed fail on my machine. All fail with similar message `Cannot read property 'address' of undefined` - probably a prequisite is missing on my machine, however, I do not know, which. Can you tell me what to look for as you better know your test setup than me. Example fail message on my machine:

```
● endpoint unit test › Registry API Endpoints › should test user api › should test add a new user

    TypeError: Cannot read property 'address' of undefined

      142 |       test('should test add a new user', (done) => {
      143 |         request(app)
    > 144 |           .put('/-/user/org.couchdb.user:jota')
          |            ^
      145 |           .send(credentials)
      146 |           .expect(HEADER_TYPE.CONTENT_TYPE, HEADERS.JSON_CHARSET)
      147 |           .expect(HTTP_STATUS.CREATED)

      at Test.Object.<anonymous>.Test.serverAddress (node_modules/supertest/lib/test.js:55:18)
      at new Test (node_modules/supertest/lib/test.js:36:12)
      at Object.obj.(anonymous function) [as put] (node_modules/supertest/index.js:25:14)
      at Object.done (test/unit/api/api.spec.js:144:12)
```

**Comment by juanpicado** [comment]
@0815fox I'll need to know more about your local environment. Actually, there are no requirements other use node (https://github.com/verdaccio/verdaccio/wiki/Build-Source-Code)

**Comment by 0815fox** [comment]
It's not that special. Debian Linux 9.5, node.js v8.11.4. I do not know "supertest" . Where does it get the address field from?

**Comment by juanpicado** [comment]
@0815fox I'm not sure why `Cannot read property 'address' of undefined` being an issue in your environment but I'm afraid I cannot do anything about it. As long the CircleCI is green and commit messages are conform our rules we can proceed with the merge.

**Pull request merged**
