### PR TITLE
fix: plugin allow_publish (pkg) got a undefined version #2313

### PR DESCRIPTION
**Pull request by sheweifan**
[#2313](https://github.com/verdaccio/verdaccio/issues/2313)

[#2310](https://github.com/verdaccio/verdaccio/discussions/2310)

### CODE REVIEW

**Comment by juanpicado** [comment]
@sheweifan thanks for the PR, I did not see it. I'll check it out this weekend.

**Comment by sheweifan** [comment]
> @sheweifan thanks for the PR, I did not see it. I'll check it out this weekend.

@juanpicado  What else do I need to do? This is my first PR。😂

**Comment by juanpicado** [comment]
@sheweifan ups sorry, I didn't realize 👍🏼 , thanks for the reminder, I'll check it later today.

**Review by juanpicado — COMMENTED** [review]
Looks good by far, I'd need to run some test to double check all is good.

**Review by juanpicado — APPROVED** [review]
LGTM, tested deeply.

**Comment by juanpicado** [comment]
Thanks @sheweifan sorry the delay, :) busy days.

**Pull request merged**
