### PR TITLE
fix: escaped slash in namespaced packages

### PR DESCRIPTION
**Pull request by amitgilad3**
in order to fix the escaped slash and make it more like the response from npm registry i removed the encodeScopedUri function which replaces in scoped url the / with %2f making in compatible with the response from npm 
close https://github.com/verdaccio/verdaccio/issues/1778 https://github.com/verdaccio/verdaccio/issues/1777

### CODE REVIEW

**Review by juanpicado — APPROVED** [review]
Thanks @amitgilad3 great stuff 💯

**Comment by juanpicado** [comment]
could you add a changeset https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#adding-a-changeset ?

**Comment by juanpicado** [comment]
One more thing, this won't be available on Verdaccio 5 after merge this, if you want to also be avilable there, then you would need a new PR over 5.x branch.

**Review by juanpicado — APPROVED** [review]
LGTM

**Comment by juanpicado** [comment]
Welcome to verdaccio world @amitgilad3 🚀

**Comment by amitgilad3** [comment]
thanks!!!!! @juanpicado ,  i hope to contribute as much as possible to this amazing product!!!

**Comment by micaelmbagira** [comment]
@juanpicado Has this been merged in v5?

**Comment by juanpicado** [comment]
Nop, only master by far (for v5 should be on 5.x)

**Pull request merged**
