### PR TITLE
Fix re-opening log files using SIGUSR2

### PR DESCRIPTION
**Pull request by marvinthepa**
port to main branch of #2966

### CODE REVIEW

**Comment by juanpicado** [comment]
Could you add a `changeset`? 
Info: https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#adding-a-changeset

**Comment by marvinthepa** [comment]
Oh sorry, I should have read CONTRIBUTING.md first.. 🙀.

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/releases/tag/v5.5.2

**Review by juanpicado — APPROVED** [review]
LGTM thanks :)

**Pull request merged**
