### PR TITLE
fix(docker): Added VERDACCIO_ prefix to docker file env in order to p…

### PR DESCRIPTION
**Pull request by kopax**
Added `VERDACCIO_` prefix to docker file environment variable in order to prevent conflict with mesos and marathon which are using `$PORT` for their internal port mapping.

### CODE REVIEW

**Comment by juanpicado** [comment]
@MichielDeMey I need your opinion here. Is this save?

**Comment by MichielDeMey** [comment]
It's indeed considered best-practice to namespace environment variables to prevent collisions.
This will however introduce a breaking change and should be accompanied with a Helm Chart change when moving forward with new versions.

@kopax Are you comfortable creating a PR in the Helm Chart repository to reflect the changes here?
https://github.com/helm/charts/tree/master/stable/verdaccio

**Comment by kopax** [comment]
@MichielDeMey I have looked at the help and read the document and unfortunately no I am not familiar with help nor kubernetes.

**Comment by MichielDeMey** [comment]
I've gave it another once-over and it looks like the Helm chart doesn't override this environment variable and sticks to the default values as specified in the `Dockerfile`.

We will however have to log this change since it will break Kubernetes deployments that override the specific environment variables.

1. We do have to change the `docker-compose.yml` file in this repository to reflect the environment variable name update.
https://github.com/verdaccio/verdaccio/blob/master/docker-compose.yaml

2. As a bonus, exposing the same set of variables in the RaspberryPi variant would be useful.
https://github.com/verdaccio/verdaccio/blob/master/Dockerfile.rpi

**Comment by juanpicado** [comment]
@MichielDeMey Ignore `Dockerfile.rpi`, unless someone takes seriously the maintenance I have plans to deprecate and remove it.

**Comment by MichielDeMey** [comment]
@kopax Can you also update the `docker-compose.yml` file with the new environment variables?

**Comment by juanpicado** [comment]
I'm agreed with this change, it's healthy, but since is a breaking change we have to be careful here. I guess Verdaccio 4 will be released this year. So, if somebody is willing to improve (cc: @sergiohgz ) Docker image this is a good moment for big changes.

**Comment by sergiohgz** [comment]
As @juanpicado said, we have an issue to improve image generation (#836). I think that it could be a great idea apply this after those changes

**Comment by kopax** [comment]
@bufferoverflow the conflict with mesos and marathons was:

1. deployment has been request throw marathon api call
1. mesos read the deployment plan and elect a slave the application can run on
1. marathon start the docker container using the defined `portMapping`, the variable `PORT` is set.
1. verdaccio docker container start and `expose $PORT`.

After that, verdaccio is starting up using the wrong port, instead of the defined in our deployment plan.

**Comment by bufferoverflow** [comment]
@kopax the behavior is correct from my perspective, marathon/mesos defines the port to listen for verdaccio, as it is the master deciding were containers should serve. What happens if portmapping within marathon/mesos is adopted to the port 4873 you want verdaccio listen to?

**Comment by kopax** [comment]
> What happens if portmapping within marathon/mesos is adopted to the port 4873 you want verdaccio listen to?

Marathon have 3 ports you can configure during the deployment, it can be understood [here](https://mesosphere.github.io/marathon/docs/ports.html)

My deployment `portMappings` generally look like this.

```sh
      "portMappings": [
        {
          "containerPort": 4873,
          "hostPort": 0,
          "protocol": "tcp"
        }
      ]
```

- `containerPort` is the port my service internally listen on.
- `hostPost` is the external port I want to force my host to use, if it's `0` then it will be automatically randomly selected from a range ports pool.

Because `hostPort` is randomly elected when it's value is `0` and `PORT` is used for letting us know what `PORT` was elected so it can be used within the docker container, then the `containerPort` which should be by default `4873` (`hostPort`) become the `containerPort` due to the conflict with `Dockerfile` environment use for starting up the container.

**Comment by dlouzan** [comment]
@bufferoverflow I agree in principle with @MichielDeMey and @kopax, I would namespace the variables with `VERDACCIO_` (did the same on the ongoing PR for dockerfile refactor).

I'm not familiar with mesos/marathon, I know how it works in k8s/openshift, and in there you have full freedom to configure your ports, both at the service and pod level, unless you are trying to expose a port on a node. Maybe some people expect that the port variable has to be `PORT`, but there's no enforcement on the k8s side and you anyway have to define explicitly your env variables in deployments, be it one name or the other.

So if mesosphere conflicts with that, I would namespace the variables. Win/win for everybody :-)

**Comment by kopax** [comment]
Sorry guys, I may have screwd up, I wanted to update the `docker-compose.yaml` as I have noticed @MichielDeMey asked for it. I see you guys made changes I've pull from 4.x and restored the change. I'm not sure if this should be close or merge so I let you decide what to do. Sorry if it messed up I did not realize I was pushing here it.

**Comment by juanpicado** [comment]
```
docker pull verdaccio/verdaccio:4.x-next
```
https://hub.docker.com/r/verdaccio/verdaccio/builds/bttavjltutdfst7bvswgonv/

**Comment by dlouzan** [comment]
I think this can be closed, prefix changes were applied in https://github.com/verdaccio/verdaccio/pull/864

**Pull request closed without merging**
