### PR TITLE
fix: hide search icon on medium or larger devices

### LINKED ISSUE #3396: Two "Search" options in header
**Your Environment**

 * **verdaccio version**: nightly-master, 5.15.3
 * **platform**: docker

**Describe the bug**

The header shows two options for searching. It's not clear which one is the correct, intended one and which should be removed.

https://github.com/verdaccio/verdaccio/blob/722c88b1d68aa9aa653adc87357d11126ccd7cb2/packages/plugins/ui-theme/src/App/Header/Header.tsx#L32-L47

**To Reproduce**

Start Web UI

**Expected behavior**

One search option is sufficient. If we keep both, they should be tied to different config settings.

**Screenshots, server logs, package manager log**

image

**Contribute to Verdaccio**

- [x] I'm willing to fix this bug 🥇

### PR DESCRIPTION
**Pull request by mbtools**
Avoids showing two search options 

Regression of https://github.com/verdaccio/verdaccio/commit/d43894e8f692ff59a11b7c376f41d939b06a5b0c

Closes #3396

### CODE REVIEW

**Review by juanpicado — COMMENTED** [review]
You need to add the changeset otherwise your change is not included in the next release, 
https://github.com/verdaccio/verdaccio/blob/master/CONTRIBUTING.md#adding-a-changeset

**Comment by juanpicado** [comment]
I'm not able to notice any to notice any difference, could you describe how to reproduce master vs this branch?

**Comment by mbtools** [comment]
Sorry, I should have paid more attention to the contribution guidelines. Let's see if I got this right...

Here's the capture where you can see how the search option works on different size devices (with the fix):

chrome_744

**Comment by juanpicado** [comment]
> Sorry, I should have paid more attention to the contribution guidelines. Let's see if I got the changeset right...
> 
> Here's the capture where you can see how the search option works on different size devices (with the fix):
> 
> chrome_744

Nice :) nowww is way more clear thanks !! LGTM

**Review by juanpicado — APPROVED** [review]

**Comment by mbtools** [comment]
don't merge, yet. looks like it works only if the registry is empty. once a package is published, the problem is still there.

**Comment by mbtools** [comment]
I guess some things were cached. Once I run with `html_cache: false`, it's working just fine. Good to merge

**Pull request merged**
